### ISSUE TITLE
right clicking after highlighting does not work

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#1]
originally submitted by @sebastien1234 

when trying to right click on highlighted text, nothing appears, should have the option to copy, CTRL-C works but most will not know to use that.

**Comment by sebastien1234** [comment]
problem still occurs in current version

**Comment by jeroenvanwissen** [comment]
This will be fixed in Public Beta 3

**Comment by dwasyluk** [comment]
pls retest in b3

**Comment by sebastien1234** [comment]
fixed in B3! closing #1
