### ISSUE TITLE
Transaction list doesn't show new transactions

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#10]
Originally submitted by @jeroenvanwissen

I was mining on testnet with the Blockmarket syscoind, and mined blocks don't show up in the transaction list. Only after application close & restart the transactions are shown.

**Comment by cmarsh599** [comment]
Comment from @sebastien1234 

same issue, received coin and no transactions showed, also created an alias and nothing, transactions appeared after wallet is closed and re-opened

**Comment by cmarsh599** [comment]
Comment from @sidhujag 

This will be fixed with a zmq integration probably around bm web.

Aliases and other services should however show up..alias right away and msg cert offer after a confirm. that is a bug if so..

**Comment by dwasyluk** [comment]
We can still improve this for Final or subsequent beta just need to look at our options with RPC and the most efficient way to get new tx info from any (native BTC or SYS specific) tx.

**Comment by sebastien1234** [comment]
Added issue #60 for refresh across the board, which once resolved, should be able to close this issue.

**Comment by sidhujag** [comment]
Retest in b4 seems to work after refactoring upsert stuff
