### ISSUE TITLE
Editing Offers throws Missing Fields" error

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#101]
If I edit an existing offer but do nothing I get an error saying required fields missing

**Comment by Keyare** [comment]
1) Editing an offer will throw "missing fields" error.
![image](https://cloud.githubusercontent.com/assets/7099087/26128651/083c9f5c-3a42-11e7-9b7a-9d42a1b76da9.png)
2) Changing the title (even to exactly the same text) allows the edit to go through
![image](https://cloud.githubusercontent.com/assets/7099087/26128715/3b7221ee-3a42-11e7-86bd-418ae9df156b.png)

**Comment by dwasyluk** [comment]
Fixed in fb087801491e07277a33bb872304a2ba1f422373 pls retest in b3.

**Comment by johnp1954** [comment]
This is fixed
