### ISSUE TITLE
Search doesn't display expected results due to character encoding in beta2

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#103]
In beta2 offer data is URI encoded before being stored, because the search strings are not being encoded they aren't matching the expected offers leading to incorrect search results. Example: "Rum Ham" is submitted as "Rum Ham" but should be submitted as the encoded "Rum%20Ham".

**Comment by dwasyluk** [comment]
I'm not encoding the search request so this may still need further improving but please retest in b3.

**Comment by phbart** [comment]
I can confirm searching for multiple words works for me in beta 3.

**Comment by sidhujag** [comment]
looks good
