### ISSUE TITLE
My marketplace purchases and items for sale - formatting issue at tablet size

### ISSUE THREAD

**Issue by Alternating** [syscoin/blockmarket-desktop-public#104]
![image](https://cloud.githubusercontent.com/assets/28740917/26129056/5722781e-3a54-11e7-823b-bac4f7f1a35b.png)

Formatting not wrapping properly

**Comment by dwasyluk** [comment]
retest in b3

**Comment by frozenfame** [comment]
<img width="1437" alt="screen shot 2017-05-30 at 9 24 40 am" src="https://cloud.githubusercontent.com/assets/29051531/26591138/edf22b5c-4519-11e7-8a1b-3ec142ec5b2e.png">

 similar issue for me in B3 with descriptions and titles, Using Mac

**Comment by sidhujag** [comment]
Yup we just need css ellipsis overflow to cap text

**Comment by dwasyluk** [comment]
Closing as fixes ellipsis text is a diff issue that applies to things outside offers as well, will create a new issue for that.
