### ISSUE TITLE
New Alias expiration field returns bad lexical cast

### ISSUE THREAD

**Issue by willyko** [syscoin/blockmarket-desktop-public#107]
When creating new alias, changing the default value in the expiration field will result in "Bad lexical cast: source type value could not be interpreted as target"

For example, current default is 
"May 16, 2018, 2:50:51 PM"
changing it to 
"May 17, 2018, 2:50:51 PM" will return the bad lexical cast error

**Comment by sidhujag** [comment]
fixed test in b4

**Comment by willyko** [comment]
beta5:  now it shows "Error: Invalid amount" instead of bad lexical cast error

**Comment by sidhujag** [comment]
retest in b5a

**Comment by willyko** [comment]
verified fix in beta5a
