### ISSUE TITLE
Viewing other people's aliases in the search results - clicking on one brings up an edit screen

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#109]
When I search for other people's aliases, I can click on one and it takes me to an Edit screen. This looks like the Create screen - the input fields are blanked and there's a Create Alias button

**Comment by Alternating** [comment]
Confirmed this .. clicked on a  user and edit came up

**Comment by Alternating** [comment]
![image](https://cloud.githubusercontent.com/assets/28740917/26130413/2aa59fb8-3a5a-11e7-8050-e61b5dc8347b.png)

**Comment by dwasyluk** [comment]
Yeah we need "view" screens for all the new seachable elements- certs and aliases.

**Comment by dwasyluk** [comment]
Fixed pls retest in b3

**Comment by sysmca** [comment]
Fixed. Although there's a new issue where this preview alias screen shows the alias balance - I'll bug it.
