### ISSUE TITLE
Back Button for marketplace navigation

### ISSUE THREAD

**Issue by ADourgarian** [syscoin/blockmarket-desktop-public#111]
An obvious "back" navigation button should be added to the marketplace while viewing orders. For instance, if I were to click on an offer, there should then be a back button that will take me to the previous page I was on.

**Comment by sidhujag** [comment]
Yea agree but not sure where to put it yet

**Comment by dwasyluk** [comment]
Does breadcrumb nav not handle this scenario?

**Comment by ADourgarian** [comment]
I love the great crumb trail it is awesome, but it isn't what people are used to. Either a back navigation or a "return to marketplace listings" button or something along those lines should be added. Also it should be added in the marketplace panel, above where the great crumb trail is(which is perfect where it is) I'll post a picture highlighting where I'm talking about tomorrow.

**Comment by ADourgarian** [comment]
Below* not above

**Comment by sidhujag** [comment]
please retest in b4
