### ISSUE TITLE
Main panels clickable and on hover icon

### ISSUE THREAD

**Issue by ADourgarian** [syscoin/blockmarket-desktop-public#112]
I think it would be more intuitive for the main panels to be clickable to navigate instead of having to click the text below them. 
![image](https://cloud.githubusercontent.com/assets/10503976/26130703/916b8a5e-3a5b-11e7-91e7-f03b9df5b576.png)

**Comment by dwasyluk** [comment]
I agree, should be an easy fix

**Comment by dwasyluk** [comment]
fixed pls retest in b3

**Comment by frozenfame** [comment]
All take to proper location except for Account Balance, That one does nothing for me.

**Comment by dwasyluk** [comment]
Fixed in 1.1.1.
