### ISSUE TITLE
On Hover navigation dropdowns

### ISSUE THREAD

**Issue by ADourgarian** [syscoin/blockmarket-desktop-public#113]
Currently you have to click on a navigation tab to get the drop down. It would be more intuitive to have an on hover dropdown.

**Comment by frozenfame** [comment]
This is working for me.

**Comment by sebastien1234** [comment]
@dwasyluk this is working, however, I haven't closed this due to your comment re: "We should disable hover menu UX in collapsed mode".

**Comment by ADourgarian** [comment]
This is excellent. Exactly what I was trying to get across. Very nice c:
