### ISSUE TITLE
Character encoding issue when you buy your own offers (using separate aliases)

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#114]
I created several aliases. I listed an item using one alias and bought it with another. In 'My Purchases' the title of the item I purchased has %20 for spaces.

**Comment by dwasyluk** [comment]
Should be fixed via the character encoding change coming in beta3, pls retest (fb087801491e07277a33bb872304a2ba1f422373).

**Comment by sysmca** [comment]
Fixed
