### ISSUE TITLE
I bought my own offer (using diff aliases) and my balance didn't update

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#116]
Listed an item with quantity 10, price 5 sys (OfferID fac6f6a9bb6ac80e).

Bought 2, then quickly bought another 2 by resubmitting the form. My balance has not updated after many confirmations.

Also, in the Items for Sale tab it shows the item with wrong 'quantity sold' data. It shows 2 sold, but I bought 4. The quantity remaining is correct, it shows 6.

**Comment by dwasyluk** [comment]
Are you referring to the alias-specific balance in the profile chooser dropdown? Or balance as displayed somewhere else?

**Comment by sidhujag** [comment]
retest in b5a

**Comment by sysmca** [comment]
Yep seems fine
