### ISSUE TITLE
Pegging not working? Bought item for 75USD, charged me 37.5 SYS

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#117]
I bought an item for 75USD (284dc17f2e6a9608) - I was deducted 37.5 SYS

1SYS = 2USD .... woot!

**Comment by willyko** [comment]
`sysadmin@pegtestnet1:~$ syscoincli aliasinfo sysrates.peg
{
  "name": "sysrates.peg",
  "value": "{\n\"rates\": [\n{\n\"currency\": \"USD\",\n\"rate\": 0.5,\n\"precision\": 2\n},\n{\n\"currency\": \"EUR\",\n\"rate\": 2695.2,\n\"precision\": 2\n},\n{\n\"currency\": \"GBP\",\n\"rate\": 2697.3,\n\"precision\": 2\n},\n{\n\"currency\": \"CAD\",\n\"rate\": 2698.0,\n\"precision\": 2\n},\n{\n\"currency\": \"BTC\",\n\"rate\": 100000.0,\n\"fee\": 75,\n\"precision\": 8\n},\n{\n\"currency\": \"SYS\",\n\"rate\": 1.0,\n\"fee\": 25,\n\"precision\": 2\n}\n]\n}\n"`

0.5 is indeed the rate right now on testnet
