### ISSUE TITLE
aliases/offers/certificates do not show after moving wallet.dat

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/blockmarket-desktop-public#118]
Important issue for anyone that wants to backup their wallet.dat

-created two aliases, certs, offers on the marketplace
-deleted all files in C:\Users\Seb\AppData\Local\Programs\Blockmarket
-deleted all files except for wallet.dat in C:\Users\Seb\AppData\Roaming\Syscoin\testnet3
-run blockmarket again
-coins are retrieved from the wallet but aliases/certificates/offers no longer appear to be owned by you and are not listed at all (offers are still searchable in browse marketplace but do not appear to be owned by you).

**Comment by dwasyluk** [comment]
This is likely because its syncing- what happens when you wait for a full sync and then close and reopen BM, is the data proper then or still incorrect?

**Comment by sebastien1234** [comment]
@dwasyluk currently a full sync and close reopen hasn't fixed the problem, I've had this issue for every new beta, since I've been using the same wallet every time, the only thing that transfers over is the balance, no aliases, no offers, no certs.

**Comment by sidhujag** [comment]
Yes its fixed in b4 not in b3

**Comment by sebastien1234** [comment]
fixed in b5, closing #118
