### ISSUE TITLE
field form validation

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#12]
Originally submitted by @sidhujag 

if the fields aren't valid they should be highlighted in red with a message under it giving the validation error (can't be empty or invalid type for example).

**Comment by dwasyluk** [comment]
Need inline user feedack when we do this. Also tooltips on form fields as contextual help.

**Comment by dwasyluk** [comment]
Fixed pls retest when b3 released.

**Comment by phbart** [comment]
This seems to work. I do however have a suggestion.

When not all required forms are filled in it is not possible to submit or create an offer, which is good. But it can be a bit unclear what exactly needs to be filled in.  It would be nice to get a bit more feedback. If I click  on the create new offer button, I would like it to show me what forms are missing for example.
