### ISSUE TITLE
Cant see my offer on the Marketplace when "SEARCH ALL"

### ISSUE THREAD

**Issue by peekay69** [syscoin/blockmarket-desktop-public#121]
I added a samsung galaxy S6 edge. But can't see it.

**Comment by sebastien1234** [comment]
What's the guid of your offer?

**Comment by sebastien1234** [comment]
![image](https://cloud.githubusercontent.com/assets/7034589/26181735/6aedda86-3b40-11e7-8580-e464494147a9.png) ?

**Comment by sebastien1234** [comment]
I see it, just search for a keyword like galaxy

**Comment by peekay69** [comment]
I see it but I don't see it on the marketplace when I search all

**Comment by sidhujag** [comment]
Only 25 offers are listed for all right now.. no paging yet
