### ISSUE TITLE
Message content has the character encode issue

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#124]
Message content is fine when looking at the list in the My Messages page:

![image](https://cloud.githubusercontent.com/assets/15713199/26201461/fef888b8-3bca-11e7-8822-dfdc71e3e632.png)

But there's a character encoding issue when you open the message:

![image](https://cloud.githubusercontent.com/assets/15713199/26201481/1d702b48-3bcb-11e7-924a-252326edce56.png)

**Comment by dwasyluk** [comment]
Fixed via fb087801491e07277a33bb872304a2ba1f422373 pls retest in beta3

**Comment by sysmca** [comment]
The message content is fine now.

However some special characters don't display properly in the preview view:

PREVIEW
![image](https://cloud.githubusercontent.com/assets/15713199/26592148/cb3772be-4557-11e7-89d6-957ddccac770.png)

MESSAGE DETAIL
![image](https://cloud.githubusercontent.com/assets/15713199/26592169/ddc1545e-4557-11e7-9c34-35d127729f56.png)

**Comment by dwasyluk** [comment]
Ah good find @sysmca I'll fix this for b4 and we can close this at that time 👍

**Comment by dwasyluk** [comment]
pls retest the specific message list encoding display (both subject and message content) for being correct in b4 :)

**Comment by sysmca** [comment]
Fixed
