### ISSUE TITLE
Recent Syscoin Transactions are not updating

### ISSUE THREAD

**Issue by peekay69** [syscoin/blockmarket-desktop-public#126]
I only see May 12th data but see May 17 data when I click on recent transactions

![1](https://cloud.githubusercontent.com/assets/28594481/26228126/eb60b250-3c04-11e7-8177-f8146c17988e.PNG)
![2](https://cloud.githubusercontent.com/assets/28594481/26228127/ed9718b6-3c04-11e7-9ab7-d22d93374084.PNG)

**Comment by sidhujag** [comment]
What was on may 17? Was it a new offer? If so this is known offer activates are not showing on front dash yet

**Comment by peekay69** [comment]
Still not fixed in Beta 3

**Comment by sidhujag** [comment]
Not a bug. recent syscoin tx's are sys services not any normal tx
