### ISSUE TITLE
Stylistic tools required for ''Description'' + larger textbox

### ISSUE THREAD

**Issue by Redrace** [syscoin/blockmarket-desktop-public#128]
When I'm in ''Description'' in "create an offer'' I would like to use the enter button to skip a blank sentence so I can divide the information. Make the description box a bit larger so you can see your whole description at once, or at least a large part of it. Very important to the seller to have customability in the description box. Think of ''bold'', ''cursive'' or other stylistic writing tools.

**Comment by Redrace** [comment]
Still not resolved if I'm correct?

**Comment by dwasyluk** [comment]
This will be in a future release >1.1
