### ISSUE TITLE
Top right aliases drop-down list does not update on receiving coins

### ISSUE THREAD

**Issue by willyko** [syscoin/blockmarket-desktop-public#134]
![screenshot 2017-05-30 18 21 44](https://cloud.githubusercontent.com/assets/11524904/26611755/2227d142-4565-11e7-9f6b-04c202d4d6da.png)

The top right drop-down list does not correspond to the txlist result

Fixes itself on restart of BM

**Comment by sidhujag** [comment]
Whats the issue?

**Comment by sidhujag** [comment]
Balances?

**Comment by willyko** [comment]
yea the balance
alias testeeertest should have 9020
alias testingaliasalias 10010
and alias testingplzdontbreak should have 10020
i checked those aliases through aliasinfo and they do have the right fund; just the UI not updated until you restart BM

**Comment by sidhujag** [comment]
Retest in b4

**Comment by sysmca** [comment]
Still a bug for me

**Comment by sidhujag** [comment]
Do you have the alias selected that should be updated? currently I only update the selected active alias, perhaps i need to go through the entire list and update the balances of all aliases... if you have your alias selected it will update that balance.

**Comment by sysmca** [comment]
yeah update all aliases i guess.

If i send syscoin to a new alias that I own, it doesn't update in the top right drop down until i re-open BM

**Comment by sidhujag** [comment]
Right ok.. makes sense.. will make that update.. so i guess it should apply to any offer accepts aswell because it will update balance paid to merchant alias which may not be selected

**Comment by sysmca** [comment]
yeah sounds good

**Comment by willyko** [comment]
fix confirmed in beta5
