### ISSUE TITLE
aliasbalance not working on api

### ISSUE THREAD

**Issue by sidhujag** [syscoin/blockmarket-desktop-public#136]
aliasbalance does not exist at the syscoin-api layer, the swagger api docs doesn't even have it but the html-core-ui shows that it exists. Please add aliasbalance as I am using it in the UI.

**Comment by dwasyluk** [comment]
Please report API issues on the [API repository](https://github.com/syscoin/syscoin-api/issues). You need to use branch dev-1.0.2, where aliasbalance is present https://github.com/syscoin/syscoin-api/blob/dev_1.0.2/server/nodejs/controllers/AliasesService.js#L51.

**Comment by dwasyluk** [comment]
You can also see that this functionality is present on the angular2-SDK-client side as well (different repo) = https://github.com/syscoin/syscoin-client-api-typescript-angular2/blob/master/api/AliasesApi.ts#L90

**Comment by sidhujag** [comment]
TypeError: Cannot read property 'apply' of undefined
    at Object.exports.aliasbalance (C:\Users\jagdeep.sidhu\Documents\GitHub\syscoin-api\server\nodejs\controllers\AliasesService.js:76:29)


Problem was that aliasbalance was being called and not aliasBalance 

see commit: https://github.com/syscoin/syscoin-api/commit/fc96700a74b845c8a774a7e939d9f5f05ca65f11

**Comment by dwasyluk** [comment]
This is fixed by the typo change in your recent commit, that was the root issue.
