### ISSUE TITLE
Transaction list 'Type' column doesn't show transaction type

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#138]
The 'Type' column in the transaction list shows 'Send' for every transaction. This should show more info on the type of transaction (alias update, offer update, offer purchase etc etc)

![image](https://user-images.githubusercontent.com/15713199/26868909-6dc532d6-4b62-11e7-91d3-9ebc69e566f3.png)

**Comment by sidhujag** [comment]
retest in b4

**Comment by sysmca** [comment]
Still exactly the same as beta 3

**Comment by sysmca** [comment]
Okay I see the transaction type is now in the ToAddress column. I was expecting to see it in the Type column

**Comment by sidhujag** [comment]
renamed to address to label, on the dashboard we really have no space to put 2 more columns, so I suggest to keep it simple for now and have one column (label)

**Comment by sysmca** [comment]
Perhaps change 'Label' to 'Description'

But otherwsie fixed
