### ISSUE TITLE
Enhancement - Alias section - Sysrate.peg and Date

### ISSUE THREAD

**Issue by Alternating** [syscoin/blockmarket-desktop-public#140]
Enhancement for the alias  creation page. 
Set sysrate.peg to a radio button and add on supported pegs btc, eth,zcash, etc etc etc <-- i'm assuming that is what sysrate is pegged to .. if i'm wrong then well I think sysrate.peg shouldn't be user defined.

Date should show the full date and time but to change it have a calendar to avoid formatting issues just like with sysrate.peg.

**Comment by sidhujag** [comment]
perhaps it should go into an advanced section

**Comment by dwasyluk** [comment]
We can add a message under the peg input on the new/edit alias screen to explain the purpose of the default value being 'sysrates.peg'.

**Comment by dwasyluk** [comment]
Since this is removed in 2.2 we'll just defer this to web rather than waste cycles improving something that will be removed.
