### ISSUE TITLE
User should be taken to new/edited entity after confirmation notification

### ISSUE THREAD

**Issue by Alternating** [syscoin/blockmarket-desktop-public#141]
When creating something new it should go to a confirmation page as say a success instead of showing the form. Some people might think their action did not go through and keep clicking create which could end up creating duplicates and costing the user more sys.

**Comment by dwasyluk** [comment]
Form buttons in b3 should disable while the form is being submitted, and only re-enable after the user is presented with a confirmation that the action succeeded. I think this would be better worded as "User should be taken to newly created entity after confirmation notification" rather then just leaving them on the form where, after the confirmation is presented to them, yes they could (user error style) click submit again and create a 2nd entry. I think we have another issue related to this , will dig it up 👍

**Comment by dwasyluk** [comment]
Similar to what happens on the "buy" form where you're taken to "My Purchases" after the confirmation is presented.

**Comment by sschepis** [comment]
The current behavior correct. When a new entity is created, the new entity screen is hidden and a toast message telling the user that the entity is being created is shown. This is what we want. We can close this issue.
