### ISSUE TITLE
Odd UX with notifications when receiving SYS transactions

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#143]
When receiving any transaction type, the recieving user is shown a "transaction pending" dialog. Only the initiating user should be shown this dialog. The receiver should be shown a green dialog after the confirmation happens and the dialog should be contextual to the receiver. 

Below is example of a seller experience as a buyer purchases an item:
![screen shot 2017-06-12 at 6 15 48 pm](https://user-images.githubusercontent.com/987186/27057803-bd1d32e2-4f9b-11e7-98e6-5e52ab245056.png)

**Comment by sidhujag** [comment]
This is how qt works, you get a notification that you got the payment, but we added an extra green one once its confirmed, so you mean to remove the green one then and just stick with the blue one?
