### ISSUE TITLE
Upsert causes application runtime error / breaks lists

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#144]
When creating a new service transaction (of any type) the upsert action is not properly updating local caches causing lists to clear or runtime errors that crash/freeze the UI. 

Can be fixed by simply quitting and reopening. Seems to happen more often as the recipient of a transaction.

**Comment by sidhujag** [comment]
Fixed retest in b4

**Comment by dwasyluk** [comment]
Fixed by refactor of WalletDataService which removed locally caching while retaining better performance and UX.
