### ISSUE TITLE
place holder graphic on top right for beta

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#15]
Originally submitted by @sidhujag 

beta should have the user profile information on the top banner on the right, placeholder if no time but it should at least be there for beta as a placeholder with tooltip saying coming in final release

**Comment by dwasyluk** [comment]
We have the balance top right but for beta 2 we should look to merge the owneraliasdropdown and profilemanager components into one, and remove owner alias selection from all screens an have it be controlled by profilemanager.

**Comment by dwasyluk** [comment]
Since we have the placeholder there in b1, im closing this as we know how this will evolve per my comment above.
