### ISSUE TITLE
'Confirm Send Money' popup too small to contain sys address

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#150]
![image](https://user-images.githubusercontent.com/15713199/27078629-4a81a240-502c-11e7-9729-8dd19f877d0a.png)

**Comment by Abuahmad007** [comment]
you should indicate in " pay to" field : payable address maybe : recipient address or alias

**Comment by Keyare** [comment]
Original issue fixed but Abuahmad007 comment not addressed

**Comment by sysmca** [comment]
Fixed
