### ISSUE TITLE
Opening Blockmarket while it's already running throws JavaScript error

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#151]
User shouldn't be able to open the wallet and get this error while an instance is already running

![image](https://user-images.githubusercontent.com/15713199/27080372-7290ff22-5033-11e7-8b82-38f439ae9e1e.png)

**Comment by dwasyluk** [comment]
This is the same thing as when Syscoin QT is running, we'll try to improve it down the line.

**Comment by doublesharp** [comment]
Catch exception when `syscoin-api` triggers and error event, force Blockmarket to close

![image](https://user-images.githubusercontent.com/571472/36634392-b98facfe-1958-11e8-9722-143db1b54674.png)

**Comment by sebastien1234** [comment]
V1.2.2:

When opening a new instance (while one is running), it appears to actually open a second instance but provides the two following error messages; clicked on "close blockmarket" and it closes the new instance. The first instance works fine, closing #151:

![image](https://user-images.githubusercontent.com/7034589/37527111-98de7ce2-2907-11e8-859e-c205c7dde2cf.png)

**Comment by dwasyluk** [comment]
* change the error message for API startup to be more friendly but still show the exact address preventing startup
