### ISSUE TITLE
Error when sending message - Failed to read to alias from alias DB

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#152]
Get this error when sending a message

![image](https://user-images.githubusercontent.com/15713199/27088233-01048d44-504f-11e7-9057-4524643144b3.png)

**Comment by sysmca** [comment]
No an issue

**Comment by Abuahmad007** [comment]
i don't know what was a problem , but when i create another alias abuahmad it works fine :)

**Comment by jeroenvanwissen** [comment]
The 'abuahmed' alias mca was sending to didn't exist or was expired.

**Comment by Abuahmad007** [comment]
why set to expired ?? i don't inderstand

**Comment by sidhujag** [comment]
maybe the expiration date was set to a near time, if you can reproduce put steps here otherwise will close this if you cant reproduce
