### ISSUE TITLE
Back button placement

### ISSUE THREAD

**Issue by frozenfame** [syscoin/blockmarket-desktop-public#155]
Back button placement looks fine when in fullscreen but when resized lower it covers over the home button. Maybe move a bit lower and it should be good.

<img width="1306" alt="screen shot 2017-06-13 at 8 50 14 am" src="https://user-images.githubusercontent.com/29051531/27105255-23b16ae0-504c-11e7-9d95-4a1e479fab4d.png">
<img width="1329" alt="screen shot 2017-06-13 at 3 18 57 pm" src="https://user-images.githubusercontent.com/29051531/27105257-250b4514-504c-11e7-803e-3e5bbde4108e.png">

**Comment by Keyare** [comment]
Back button now in Navigation menu.
