### ISSUE TITLE
No display of conversion from USD to SYS before purchase

### ISSUE THREAD

**Issue by jjbaker13** [syscoin/blockmarket-desktop-public#158]
When purchasing an item listing in USD, there is no way to know if you have enough sys to purchase.
Needs some kind of conversion rate button or list of currency conversion.
![screenshot 2017-06-28 10 07 58](https://user-images.githubusercontent.com/29758343/27650556-2afcd1e6-5bea-11e7-9102-1d8829037cfc.jpg)

**Comment by dwasyluk** [comment]
Nice to have for 1.0, will shoot for 1.1 solid.

**Comment by dwasyluk** [comment]
Fixed in main display and confirmation shows SYS price * qty too.

**Comment by willyko** [comment]
I see it fixed in main display as "PRICE: 29.00 USD / 14.50 SYS"
I think "PRICE: 29.00 USD ( 14.50 SYS )"  is more intuitive
or with more detail "PRICE: 29.00 USD ( 14.50 SYS @ 2.00 USD/SYS )
