### ISSUE TITLE
"My Purchases" sub-folder title does not match

### ISSUE THREAD

**Issue by jjbaker13** [syscoin/blockmarket-desktop-public#159]
In "My Marketplace" >> "My Purchases" sub-folder has a different title ("Purchased Items"). 

![screenshot 2017-06-28 10 04 20](https://user-images.githubusercontent.com/29758343/27650700-881fd5bc-5bea-11e7-8b3d-b88d3d48cb03.jpg)

**Comment by sidhujag** [comment]
retest in b5a

**Comment by willyko** [comment]
fix confirmed
