### ISSUE TITLE
Browse Marketplace is under "My Marketplace" category 

### ISSUE THREAD

**Issue by jjbaker13** [syscoin/blockmarket-desktop-public#165]
"Home / My Marketplace / Browse Marketplace"

Browse Marketplace is within "My Marketplace" category. Should be under its own "Marketplace" category or a main/home Marketplace page.

![marketplace](https://user-images.githubusercontent.com/29758343/27655189-5aa2da6c-5bf9-11e7-8f05-1d38ccfb342d.jpg)

**Comment by sidhujag** [comment]
retest in b6

**Comment by willyko** [comment]
fix confirmed!
