### ISSUE TITLE
Some pictures in Browse Marketplace stretched out

### ISSUE THREAD

**Issue by frozenfame** [syscoin/blockmarket-desktop-public#167]
After i updated my offer the picture ended up stretched out in the browse marketplace page which caused all other offer boxes to stretch out. Some of the other pictures also have a similar problem. I tried deleting the picture and re-adding it, still stretched.

Once in the offer page pictures look fine.

<img width="1418" alt="screen shot 2017-07-06 at 9 10 20 pm" src="https://user-images.githubusercontent.com/29051531/27941803-bdb29c86-628f-11e7-8c91-002862049af5.png">

**Comment by sidhujag** [comment]
retest in b6(rc1)

**Comment by willyko** [comment]
fix confirmed
