### ISSUE TITLE
Breadcrumb links don't work in Escrow detail page

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#169]
Breadcrumb links don't work in Escrow detail page

![image](https://user-images.githubusercontent.com/15713199/27946584-5ef2371e-62ea-11e7-88b8-ab2a0048871e.png)

**Comment by sidhujag** [comment]
made it consistent with offers, removed those extra non working routes, it should show as marketplace / guid, perhaps later we can have seperate routes for the different screens like escrow details coming from my purchased escrows vs sold escrows so you can click to go back (although back button does take you back there)

**Comment by sidhujag** [comment]
retest in b5a

**Comment by sysmca** [comment]
Yep fine
