### ISSUE TITLE
notifications don't go away until clicked

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#17]
Originally submitted by @sidhujag 

The little notifications that popup after transactions are complete do not go away until they are clicked... also on chrome on windows there are disabled scrollbars on the side and bottom (no screenshot available), is there a way to ensure no scrollbars show no matter what? You can set that in the CSS for it.

**Comment by dwasyluk** [comment]
This is fixed, the auto-close after 5s.
