### ISSUE TITLE
Breadcrumb links in Messages tab inbox page aren't right

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#170]
The My Messages breadcrumb item links to the same page as the inbox - leading to unexpected behaviour when clicking on these links

![image](https://user-images.githubusercontent.com/15713199/27946712-da77faae-62ea-11e7-9941-250c69e76f6e.png)

**Comment by sidhujag** [comment]
we have to rethink messages because I have discovered a better way to do them. Probably going to strip them out and introduce them in 2.2
