### ISSUE TITLE
Encrypting wallet crashes wallet

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#171]
Encrypting the wallet crashes the wallet on Windows 10 64bit

**Comment by frozenfame** [comment]
Same problem on Mac.

**Comment by sebastien1234** [comment]
confirmed, windows 10 64 bit crashes with no error message.

**Comment by sidhujag** [comment]
More info please.. its supposed to close first time. Is it reproducible what are the steps?

**Comment by sysmca** [comment]
Okay needs to be more obvious that the software shuts itself down when you encrypt then. Seemed like a crash to me

**Comment by sidhujag** [comment]
Oh ok i think svliege is going to make it autorun again

**Comment by dwasyluk** [comment]
This is operating as expected. There is a bold message as the last line in the encryption dialog stating THE WALLET WILL CLOSE. Already have plans to make this experience better but for now closing, this is not a crash.

**Comment by sysmca** [comment]
Cool. Obviously worth noting that 3 of us missed the message!
