### ISSUE TITLE
The wallet lock/unlock process is very confusing

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#172]
When wallet is in locked state you click it to unlock and enter your password. When you click the green open padlock icon the wallet unlocks but you are immediately confronted with a Lock Wallet drop down. I've just unlocked the wallet, I don't want to lock it again yet :)

Same thing when I click the orange icon to lock the wallet - immediately I get a popup password to unlock the wallet ...

**Comment by dwasyluk** [comment]
Fixed in 1.1.1.
