### ISSUE TITLE
Encrypt Wallet

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#173]
Although the hint says you must use a minimum of 10 characters it allows you to use less, I used 8

**Comment by dwasyluk** [comment]
This will be fixed and was also mentioned in the security audit findings by DBG.

**Comment by dwasyluk** [comment]
The message is just a recommendation, we can update the phrasing.

**Comment by dwasyluk** [comment]
@johnp1954 this should be fixed, please retest and close.
