### ISSUE TITLE
Description text overflows out of screen (+ incorrect decoded data)

### ISSUE THREAD

**Issue by timelessdesign** [syscoin/blockmarket-desktop-public#177]
When viewing this specific item, the description was decoded incorrectly which causes the text to overflow out of the box/screen.

<img width="1436" alt="screen shot 2017-07-08 at 20 50 10" src="https://user-images.githubusercontent.com/30006325/27987953-83b1add8-641f-11e7-8d6d-895c7b21568f.png">

**Comment by sidhujag** [comment]
retest in b6(rc1)

**Comment by willyko** [comment]
fix confirmed
