### ISSUE TITLE
Alias 'Expires In' in seconds

### ISSUE THREAD

**Issue by timelessdesign** [syscoin/blockmarket-desktop-public#178]
Perhaps 'seconds' is not the best format to use here.

<img width="516" alt="screen shot 2017-07-08 at 20 30 10" src="https://user-images.githubusercontent.com/30006325/27988016-c7cc5288-6420-11e7-9324-38c2a3b629d1.png">

**Comment by sidhujag** [comment]
retest in b6(rc1)

**Comment by dwasyluk** [comment]
Should display as human date.

**Comment by sidhujag** [comment]
retest in b6

**Comment by willyko** [comment]
fix confirmed
