### ISSUE TITLE
Empty Offer Purchase Information after Purchasing with Escrow

### ISSUE THREAD

**Issue by timelessdesign** [syscoin/blockmarket-desktop-public#180]
Got redirected to an empty information screen after purchasing an item with escrow.

<img width="1440" alt="screen shot 2017-07-08 at 23 50 03" src="https://user-images.githubusercontent.com/30006325/27989134-a1aa15c6-643a-11e7-89b1-fa3e82e26873.png">

**Comment by sidhujag** [comment]
retest in b6(rc1)

**Comment by willyko** [comment]
fix confirmed.  Now after blockchain confirmation, you'll get redirected to escrow info
