### ISSUE TITLE
ERRCODE 1507 - 'Certificates' category not valid when creating a new offer selling a certificate

### ISSUE THREAD

**Issue by timelessdesign** [syscoin/blockmarket-desktop-public#181]
ERRCODE 1507: "Offer selling a certificate must use a certificate category".
Even though I selected the category 'Certificates > Gift Card' (or even just 'Certificates' for that matter), the selected category did not get recognised as valid and could not create the offer.

<img width="1440" alt="screen shot 2017-07-08 at 23 36 50" src="https://user-images.githubusercontent.com/30006325/27989166-6f69ce2a-643b-11e7-86d2-85d499198382.png">

**Comment by sidhujag** [comment]
Fixed in b6(rc1)

**Comment by willyko** [comment]
fixed confirmed in beta6
