### ISSUE TITLE
Confirmation window needed when releasing escrow

### ISSUE THREAD

**Issue by timelessdesign** [syscoin/blockmarket-desktop-public#182]
When clicking on the 'Finalize' button to release escrow, a confirmation window would be desired asking the user "Are you sure you want to release the escrow?" since there is no way to cancel the action.

<img width="1440" alt="screen shot 2017-07-09 at 0 28 59" src="https://user-images.githubusercontent.com/30006325/27989272-f29be9ac-643d-11e7-9af0-447d55506a99.png">

**Comment by sidhujag** [comment]
retest in b5a

**Comment by willyko** [comment]
fix confirmed
