### ISSUE TITLE
Finalize escrow button let's you release escrow multiple times

### ISSUE THREAD

**Issue by timelessdesign** [syscoin/blockmarket-desktop-public#183]
In the 'Purchases in Escrow' section, perhaps the 'Finalize' button could be disabled after activating it already once. In the notification dropdown (see image below), the escrow is being released 3 times now. (Also mentioned in another issue, a confirmation window here would be very helpful).

<img width="328" alt="screen shot 2017-07-09 at 0 35 56" src="https://user-images.githubusercontent.com/30006325/27989327-d3a93d82-643e-11e7-8007-6c8da8806322.png">

**Comment by sidhujag** [comment]
fix retest in b5a

**Comment by willyko** [comment]
fix confirmed. Recent activity no longer has duplicate escrow released when clicked on finalize multiple times
