### ISSUE TITLE
Sending SYS to an invalid alias give inaccurate error message

### ISSUE THREAD

**Issue by cbassthefish1** [syscoin/blockmarket-desktop-public#184]
Sent SYS to an invalid alias. Gave error message that it was an "invalid SYS address". SYS addresses are not the same as aliases.

**Comment by sidhujag** [comment]
test this in bm web, perhaps rework the error messages in core

**Comment by dwasyluk** [comment]
Deferring to web. Added to syscoin/syscoin2 as issue.
