### ISSUE TITLE
Creating new alias gives no confirmation. With the following parameters.

### ISSUE THREAD

**Issue by cbassthefish1** [syscoin/blockmarket-desktop-public#186]
Creating new alias gives no confirmation. With the following parameters.

![image](https://user-images.githubusercontent.com/28635358/27997681-74cf326c-6506-11e7-9ffa-dacd960a8398.png)

Alert stays pending:

![image](https://user-images.githubusercontent.com/28635358/27997692-9ca16828-6506-11e7-9464-08acc30fd708.png)

Have to exit and re-start BM for it to update.

**Comment by sidhujag** [comment]
Plz try to reproduce it could just be a random error.. and wait until 2 or 3 minutes to see if its fixed

**Comment by dwasyluk** [comment]
@cbassthefish1 were you able to reproduce?

**Comment by dwasyluk** [comment]
Closing as beta.
