### ISSUE TITLE
Listing error, pictures being stretched out

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/blockmarket-desktop-public#187]
Blockmarket 1.0.0-Beta5a: Browse Marketplace issues with displaying listings, it appears that certain pictures make the listing much larger, see example of 4 pictures below, it took 4 pictures to show the entire "tim hortons cup" listing.

![image](https://user-images.githubusercontent.com/7034589/28250515-695d416c-6a38-11e7-9b96-0bcf838b0ad3.png)
![image](https://user-images.githubusercontent.com/7034589/28250517-802edc2a-6a38-11e7-81e4-5088520f5368.png)
![image](https://user-images.githubusercontent.com/7034589/28250520-95621cf6-6a38-11e7-9958-8b8d9b8d8720.png)
![image](https://user-images.githubusercontent.com/7034589/28250521-a24a94ca-6a38-11e7-80da-bb1ca65446e4.png)

**Comment by sidhujag** [comment]
Looks fine on mine

**Comment by johnp1954** [comment]
All stretched on mine Win 10 64bit 1366 X 768 res

**Comment by sidhujag** [comment]
Johnp we are on b5a you dont have b5a i think

**Comment by sebastien1234** [comment]
close fixed in b5a

**Comment by dwasyluk** [comment]
Critical label should only be applied to show-stopper issues (unable to create transactions, incorrect data display, full on crashes, etc). This is high-priority for sure.
