### ISSUE TITLE
change wording after purchase

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/blockmarket-desktop-public#188]
Blockmarket 1.0.0-Beta5a

After clicking "buy now" for a purchase, wording should be changed regarding confirmations. Currently says "Waiting for confirms, typically takes 60 seconds" should be changed to "Waiting for blockchain confirmation, approximately 60 seconds wait-time"

![image](https://user-images.githubusercontent.com/7034589/28250700-279db8c4-6a3d-11e7-91cb-d5c543b96c6a.png)

**Comment by sidhujag** [comment]
fixed, retest

**Comment by sebastien1234** [comment]
fixed, closing #188
