### ISSUE TITLE
If escrow is not selected, prompt should follow

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/blockmarket-desktop-public#189]
When clicking "Buy Now" to an offer when you haven't selected "secure purchase with escrow", prompt should follow asking "Are you sure that you do not want to use an arbiter to secure this transaction? Please make sure you trust the merchant if you do not select an arbiter."

**Comment by sebastien1234** [comment]
Not fixed in Beta 5c

**Comment by dwasyluk** [comment]
@sebastien1234 this should be fixed, please retest and close.

**Comment by sebastien1234** [comment]
close #189
