### ISSUE TITLE
Document the official blockmarket JSON offer spec

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#19]
Originally submitted by @dwasyluk 

Blockmarket can only read items that are formatted to a particular JSON spec, this spec should be published on the wiki here.

**Comment by dwasyluk** [comment]
To be more specific as of Blockmarket offer.description will be a JSON object, not a normal string. This format will allow us to cleanly store seperate data related to description such as images, description, handling time, etc without having to introduce hardforks.

The implementation of this should be backwards compatible with "non spec" offer descriptions in which case BM will just display the description and attempt to parse 1 image from the description text as a display image.

**Comment by dwasyluk** [comment]
Documented at https://github.com/syscoin/blockmarket-desktop-public/blob/master/README.md#blockmarket-offer-json-spec
