### ISSUE TITLE
Prompt should pop-up when finalizing escrow

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/blockmarket-desktop-public#190]
When clicking on the "finalize button" under "purchases in escrow", a prompt should appear asking the user the following question. "Clicking "Finalize" on this offer will release the offer to the merchant. Are you sure that you want to complete this transaction now?"

**Comment by sidhujag** [comment]
Retest in b5a please

**Comment by sidhujag** [comment]
is this fixed?

**Comment by sebastien1234** [comment]
fixed #190 in b5c
