### ISSUE TITLE
scrolling should always default to top on an offer listing

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/blockmarket-desktop-public#193]
when clicking on an item to purchase, scrolling should default at the top of the page every time. 

Example here, 1st picture is under "browse marketplace" scrolled down to the bottom, when clicking on the "tim hortons cup" offer, the scrolling defaults to the same point of the page (bottom) on the clicked offer (see second image), when clicking on an offer it should always scroll back to the top or it does not look very clean.

![image](https://user-images.githubusercontent.com/7034589/28254996-1f0338b8-6a80-11e7-98e8-3a5cfbc82c2d.png)

![image](https://user-images.githubusercontent.com/7034589/28255012-3b0f7a76-6a80-11e7-9522-4903f99e6dcc.png)

**Comment by sidhujag** [comment]
fixed please retest

**Comment by sebastien1234** [comment]
fixed in beta 5c
