### ISSUE TITLE
New Offer Price cannot be under 1 

### ISSUE THREAD

**Issue by willyko** [syscoin/blockmarket-desktop-public#194]
Listing an offer with a price under 1 will result in greyed out "Create New Offer" button (anything from 0~1) 

To repro, set Offer title, offer description, and offer category.  The "Create New Offer" button will turn active.

Now, change the number in the price field to say, 0.5, and you'll see the "Create New Offer" grey out.

**Comment by willyko** [comment]
edit offer also has the same issue

**Comment by sidhujag** [comment]
fixed, min is 0.01 now

**Comment by willyko** [comment]
![screenshot 2017-07-25 11 27 40](https://user-images.githubusercontent.com/11524904/28587540-60a54484-712c-11e7-9298-ed3ea9be8c7b.png)

marketplace listing shows 0.00
also... 0.00001 seem to work only with currencies that's not SYS.  I get error code 1505: could not find currency in peg alias
