### ISSUE TITLE
Cannot copy Offer ID

### ISSUE THREAD

**Issue by Keyare** [syscoin/blockmarket-desktop-public#199]
![image](https://user-images.githubusercontent.com/7099087/28641781-41c3c322-7205-11e7-8531-dd4acedd4010.png)

PC - when trying to copy the offer ID the result is "About Blank"

**Comment by sidhujag** [comment]
You were not copying offer ID you were copying the link. You did a right click copy right?

**Comment by Keyare** [comment]
The context menu with "copy link" should copy the offerID text

**Comment by sidhujag** [comment]
You can copy the text by highlitghting it, not worth the time to do in electron, and web will work ootb.
