### ISSUE TITLE
sending syscoin to an alias does not work

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#2]
originally submitted by @sebastien1234 

When sending to "danosphere' received the following error

![image](https://cloud.githubusercontent.com/assets/24413854/25870986/fb73a98c-34d3-11e7-84d6-04742a5d3ecc.png)

**Comment by dwasyluk** [comment]
This should be fixed in beta1, please retest and close or provide further details on what happens @sebastien1234 .

**Comment by sebastien1234** [comment]
works now, close #2
