### ISSUE TITLE
Unlimited quantities cannot be edited. 

### ISSUE THREAD

**Issue by Keyare** [syscoin/blockmarket-desktop-public#200]
UI does not allow 0 quantity or -1 (for unlimited) 
and unlimited quantity offers created in core cannot be edited in BM.

UI should indicate that the user needs to set to -1 for unlimited quantities
*or*  do not allow <1 quantites but add an "unlimited" button and "delete" button.

**Comment by sidhujag** [comment]
retest

**Comment by dwasyluk** [comment]
Closing as its from beta.
