### ISSUE TITLE
Fix public data listing in certificates search

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/blockmarket-desktop-public#202]
clicking on somone elses certificate, the listing is not super clear as there should be a "Public data:" section prior to the public data being listed, example below shows a certificate I do not own 2360a15e19f5a639 which shows the public data as "MyTunes Gift Card 25&#x20AC", should really say "Public Data: MyTunes Gift Card 25&#x20AC"

![image](https://user-images.githubusercontent.com/7034589/28649579-02734104-7244-11e7-8875-41a53db7780f.png)

**Comment by sidhujag** [comment]
retest
