### ISSUE TITLE
Set label of sending address through the send coins page doesn't work

### ISSUE THREAD

**Issue by sidhujag** [syscoin/blockmarket-desktop-public#206]
setaccount rpc is not available through our api which we could have used to set the account (label) of the sending address. Currently QT adds the label to the address book upon the qt send coins dialog, which is not connected to the RPC in any way. To fix we would enable setaccount through API and add the call to setaccount if label was set upon sending coins.

**Comment by dwasyluk** [comment]
Label field has been removed and will be reintroced through an address-book feature in BM in future release.
