### ISSUE TITLE
Dashboard' recent blocks TXs column has unit of SYS in each row

### ISSUE THREAD

**Issue by willyko** [syscoin/blockmarket-desktop-public#207]
![screenshot 2017-07-28 17 14 44](https://user-images.githubusercontent.com/11524904/28740326-55e623e0-73b8-11e7-90c8-1b41c4c6a39c.png)

Home Page dashboard's Recent Blocks, I believe the third column is meant to be number of transactions within the block instead of "SYS"

**Comment by sidhujag** [comment]
retest
