### ISSUE TITLE
Navigation stops working

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#21]
Originally submitted by @Keyare 

Windows 0.1.5 - Selecting Marketplace->Browse Marketplace stops navigation dropdowns from working. Possibly a conflict with the categories dropdown on that tab.

**Comment by sidhujag** [comment]
this has been fixed, please retest on latest

**Comment by dwasyluk** [comment]
Marking as closed as reported as such by @cmarsh599
