### ISSUE TITLE
Certificates: possible to transfer certificate more than once

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#210]
After you transfer a certificate, the 'Transfer' button becomes inactive, stopping you from transferring the same cert twice. Awesome. BUT .. if you navigate somewhere else in the wallet and come back the My Aliases tab, the Transfer button is active again and you can transfer the cert again.

The cert is transferred to whoever was chosen in the second transfer. The transaction takes place and appears in the TX list, however it doesn't appear in the Recent Activity drop down.

**Comment by dwasyluk** [comment]
Fixed and ready for internal test, also fixed a number of other unreported bugs related to cert xfter popup/experience.

**Comment by willyko** [comment]
Fix confirmed.  The transfer button now remains disabled for the transferred certificate after navigating away from the screen.
