### ISSUE TITLE
Aliases: breadcrumb is wrong after searching for aliases

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#211]
steps:

- go in to alias search
- search 'dan', observe breadcrumb
- click on one of the search results, observe broken breadcrumb

![image](https://user-images.githubusercontent.com/15713199/29171425-7b2b3264-7dd4-11e7-8098-e6901f705cc0.png)

**Comment by sidhujag** [comment]
how is it broken? They seem to all work still

**Comment by sysmca** [comment]
it's just illogical, 'dan' and 'details' server the same purpose

should be Home > Alias Search > Results > danosphere

or something like that

**Comment by sidhujag** [comment]
for this we need to use hideRouteRegex to hide the details route. Dan want to take a look?

**Comment by willyko** [comment]
restest in beta 6

**Comment by willyko** [comment]
fix confirmed!
