### ISSUE TITLE
Browse Marketplace - Paging - No end of results.

### ISSUE THREAD

**Issue by Keyare** [syscoin/blockmarket-desktop-public#212]
The last page of unique offers is roughly 51-60 but if you click Next it goes to the previous page, but shows 61-70.

keep hitting Next Page and it will go back and forth between the last two sets of ten results.

ALSO: can we make it 12 results so that there aren't two dead spots?

**Comment by sidhujag** [comment]
cant reproduce

**Comment by willyko** [comment]
open the ALSO part as a separate issue?

**Comment by Keyare** [comment]
Reproduced.
