### ISSUE TITLE
Notifications show transactions from old wallet

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#213]
I created a brand new wallet and in the notifications area (bell icon) I saw transactions from my previous wallet.

Steps:

1. Create a wallet - perform some transactions
2. Close wallet
3. Delete the wallet.dat
4. Open wallet
5. Observe your transactions from the old wallet

(beta 5f)

**Comment by dwasyluk** [comment]
We'll change how recent activity works to pertain only to your active session. Since it was prev storing actions from other sessions that was the cause of this bug.

**Comment by sidhujag** [comment]
retest

**Comment by dwasyluk** [comment]
Closing as its from beta times.
