### ISSUE TITLE
Dropdowns have scrollbars on Windows

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#22]
Originally submitted by @Keyare 

![image](https://cloud.githubusercontent.com/assets/24413854/25872648/8b80cab4-34d9-11e7-8ec8-05e7f3003cfa.png)

**Comment by sidhujag** [comment]
I fixed this , next beta will have this in there.

**Comment by dwasyluk** [comment]
Fixed in b2.
