### ISSUE TITLE
Price to list in which Currency is not intuitive

### ISSUE THREAD

**Issue by Keyare** [syscoin/blockmarket-desktop-public#220]
![price](https://user-images.githubusercontent.com/7099087/29786508-4196b662-8be0-11e7-9dae-b89249003302.png)
The current form layout has "Price" then two other form fields before you choose what currency to list the item in.  Currency-to-list-in should be directly under, or directly beside Price as it is easily confused with "Payment options". This needs to be clearer to the user. Payment options and Currency need clear direction as to their purpose.

Suggest: 
List in: 
Accepted Currencies:

**Comment by sidhujag** [comment]
retest
