### ISSUE TITLE
Messages: number of sent items doesn't show until you click on sent items

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#221]
![image](https://user-images.githubusercontent.com/15713199/30239284-e143b7fe-9550-11e7-903f-a00f4f982c43.png)

![image](https://user-images.githubusercontent.com/15713199/30239289-ff0d92d2-9550-11e7-85b4-758996d4ca18.png)

**Comment by sidhujag** [comment]
retest in latest

**Comment by sysmca** [comment]
fixed
