### ISSUE TITLE
Escrow: Release to seller - 'No' button doesn't do anything

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#222]
When you release to seller but click 'No', nothing happens

![image](https://user-images.githubusercontent.com/15713199/30242232-a60a5366-958a-11e7-8966-bcf9b8bae222.png)

**Comment by sidhujag** [comment]
retest in latest

**Comment by sysmca** [comment]
fixed

**Comment by sysmca** [comment]
fixed
