### ISSUE TITLE
Certificates: Private Value field content is garbled nonsense after updating that field

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#223]
After updating the private value field of a cert, it's contents are garbled junk:

![image](https://user-images.githubusercontent.com/15713199/30250706-fe925d38-964a-11e7-8659-419e32a7f625.png)

**Comment by sysmca** [comment]
In fact the private value field of ALL my certificates now contains garbage

**Comment by sidhujag** [comment]
Did you do a transfer on the affected certs?

**Comment by sidhujag** [comment]
Did you do a transfer on the affected certs?

**Comment by dwasyluk** [comment]
@sysmca is this still an issue in 1.1.1?
