### ISSUE TITLE
Blockmarket 1.0.0 won't load under Mac OS ElCapitan

### ISSUE THREAD

**Issue by stvn100** [syscoin/blockmarket-desktop-public#226]
Hello guys,

some of the Mac users including me have reported on Twitter that the Mac version gets stuck while loading (see picture):
<img width="1003" alt="screen shot 2017-09-12 at 4 28 11 pm" src="https://user-images.githubusercontent.com/31903922/30349122-6db5ec7e-97d7-11e7-9987-2c21d40912ff.png">

I can confirm that I found and removed the complete Syscoin folder in folder Application Support prior to installing Blockmarket.

Please help.

Thx.

**Comment by sidhujag** [comment]
check to ensure syscoind isn't already running before launching... ensure no blockmarket or syscoind is running, then rerun it

**Comment by einalex** [comment]
enhancement proposal: try to read files with a timeout and spawn an appropriate error message ("couldn't access files, please close other wallets..") if timeout is reached.

**Comment by stvn100** [comment]
Issue solved. Blockmarket 1.0.0 is apparently not supported under ElCapitan. Needed to update Mac OS to Sierra.

**Comment by birchcode** [comment]
+1 

Upgrading to sierra shouldn't be the solution. Many, many users like myself don't upgrade to the latest osx.

**Comment by CyberMew** [comment]
How much extra work should it be to support OS X El Capitan?

**Comment by jeroenvanwissen** [comment]
A solution for this is in the works

**Comment by sidhujag** [comment]
Please try latest binary.. it should work

**Comment by dwasyluk** [comment]
Closing as yet another occurence of #264
