### ISSUE TITLE
Certificate Error when switching to All Accounts

### ISSUE THREAD

**Issue by frozenfame** [syscoin/blockmarket-desktop-public#228]
<img width="363" alt="screen shot 2017-09-12 at 10 40 19 pm" src="https://user-images.githubusercontent.com/29051531/30359996-eb5a35e8-980b-11e7-9d72-e66dce0f1575.png">

See screenshot. This occured when switching from my main "frozenfame" account to "All Accounts" from the upper dropdown menu.

**Comment by sidhujag** [comment]
retest in 1.1

**Comment by sidhujag** [comment]
Dup of #236
