### ISSUE TITLE
Blockmarket "Receiving" addresses panel shows both receiving and sending addresses

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#23]
Originally submitted by @Keyare 

Blockmarket "Receiving" addresses panel shows both receiving and sending addresses.

![image](https://cloud.githubusercontent.com/assets/24413854/25872693/a94cb260-34d9-11e7-8b4b-c63b2a80c8b4.png)

**Comment by dwasyluk** [comment]
@Keyare I need your QT console results for `listreceivedbyaddress` to debug this. Please include console output JSON snippet and QT receiving address panel when u get a chance. Lmk how far off they look, internal team reports this all looks correct.

**Comment by sebastien1234** [comment]
can confirm not happening for me in Blockmarket 1.0.0-Beta5a, @Keyare are you still having this issue?

**Comment by willyko** [comment]
fix confirmed
