### ISSUE TITLE
Deleting Blockmarket.exe

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#234]
Trying to delete Blockmarket.exe on Win 10 64 bit and cannot as it says it is in use. Check Task manger and it is not running however go to Details are there are suspended processes 
![image](https://user-images.githubusercontent.com/16462796/30395877-985b5962-98bf-11e7-8a00-0e890217c50c.png) and i cant remove them as access is denied

**Comment by sidhujag** [comment]
Try to end blockmarket.exe tasks, all 3 of them

**Comment by dwasyluk** [comment]
Closing as there seems to be no further occurence of this.
