### ISSUE TITLE
Balance showing incorrectly in BM 1

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#235]
This is a copy from #help win 10 64 bit

![image](https://user-images.githubusercontent.com/16462796/30402063-6cb5fa00-98d4-11e7-864b-1bd32de1bdb4.png)
This made me panic

![image](https://user-images.githubusercontent.com/16462796/30402087-8463fe4a-98d4-11e7-9a96-199eaee34db1.png)

This gave me a heart attack

Go to another screen like messages and come back and my balance is correct

downloading the whole things again didnt fix the amount issue looks like it has something to do with going to and from different areas

**Comment by sidhujag** [comment]
you mean afteryou synced up it showed wrong balances? when you restart it should be ok?

**Comment by johnp1954** [comment]
Yes fully synced and no difference when you restart it

**Comment by dwasyluk** [comment]
This is an issue w how the UI is calling getbalance and is purely visual fwiw. We need to be passing null instead of "" or "*" @sidhujag. I agree its def still critical fix just for optics reasons but at a functional level you have all your sys, and you can't overspend or anything.

**Comment by dwasyluk** [comment]
This is fixed by getwalletbalance and is now ready for internal retest

**Comment by willyko** [comment]
fix confirmed
