### ISSUE TITLE
When sending a message to someone without unlocking the wallet the message will not be able to send anymore. Closing of message required. (bug)

### ISSUE THREAD

**Issue by Redrace** [syscoin/blockmarket-desktop-public#239]
Should speak for itself.

**Comment by willyko** [comment]
Reproduced:
Sending message while wallet is locked, the "SEND" button will remain gray-ed out and one will have to navigate out and back in the clear it.

**Comment by dwasyluk** [comment]
All submit buttons are now disabled w/tooltip until the wallet is unlocked.

**Comment by willyko** [comment]
Fix confirmed
