### ISSUE TITLE
Price pegging not stable? (bug)

### ISSUE THREAD

**Issue by Redrace** [syscoin/blockmarket-desktop-public#240]
Offer ID: f1548a0df596375c

I put a wanted offer for the solar panels pegged for 5000 euro. After a day the system pegged it to 4710 euro. Something is not right here.

**Comment by sidhujag** [comment]
Yeah the system was redeveloped in 2.2 core, it was storing syscoin amounts and not pegged amounts, so when the underlying price changed the syscoin amounts changed as well. This is fixed in 2.2 core
