### ISSUE TITLE
macOS Sierra - 10.12.6 not loading on startup

### ISSUE THREAD

**Issue by Nova8** [syscoin/blockmarket-desktop-public#245]
<img width="998" alt="screen shot 2017-09-15 at 23 27 23" src="https://user-images.githubusercontent.com/10305849/30505591-7dd5378e-9a6d-11e7-838b-63dc61759e20.png">

First time adding wallet, Cogs spin for hours.

**Comment by sidhujag** [comment]
use 1.0.1

**Comment by Nova8** [comment]
I can't see 1.0.1 on the Code Tab, any directions thanks?

**Comment by sidhujag** [comment]
try this link https://github.com/syscoin/blockmarket-desktop-public/releases/tag/1.0.1

**Comment by dwasyluk** [comment]
@Nova8 if 1.0.1 does work for you please close this issue, thanks! If not let us know and we'll investigate further 👍

**Comment by Nova8** [comment]
Thanks it worked
