### ISSUE TITLE
"Sending Address List" missing from menu

### ISSUE THREAD

**Issue by cryptme00** [syscoin/blockmarket-desktop-public#246]
Tested with Blockmarket 1.0.1 (https://github.com/syscoin/blockmarket-desktop-public/releases/download/1.0.1/Blockmarket-Setup-1.0.1.exe) on Win10x64
The "Sending Address List" menu is missing from the menu.
![image](https://user-images.githubusercontent.com/26304225/30518404-fd7a38e0-9b85-11e7-997c-2b0dc37d7ada.png)

**Comment by sidhujag** [comment]
Use aliases instead. No sending alias menu required.

**Comment by sidhujag** [comment]
I think we can store sent addresses in localstorage

**Comment by dwasyluk** [comment]
Address book is a feature we may add in a future release/web.
