### ISSUE TITLE
When pusing the ''next page'' to fast in the blockmarket the whole app bugs out. 

### ISSUE THREAD

**Issue by Redrace** [syscoin/blockmarket-desktop-public#247]
![bm](https://user-images.githubusercontent.com/29055754/30660468-2896a83e-9e41-11e7-8c91-3c6c08e497dd.png)

Look at the lsiting counter: 1400 (there aren't that many offers.) 
If I keep pressing the ''next page'' button the system continues to count, but remains switching betweetn two pages of offers.

**Comment by dwasyluk** [comment]
Fixed in 1.1.1.
