### ISSUE TITLE
Blockchain sync progress bar is inaccurate

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#255]
When you first open BM the progress  bar shows 100% sync'd

![bm_sync_issue_01](https://user-images.githubusercontent.com/15713199/32098168-c1959886-bb03-11e7-90d9-7c276db4e373.png)

BM seems to synch in the background and only updates block display and progress when it's finished

![bm_sync_issue_02](https://user-images.githubusercontent.com/15713199/32098224-efa4ec9a-bb03-11e7-85ee-a5bf4a6e016b.png)

**Comment by willyko** [comment]
Fix confirmed.  Now on startup the bar will read "Waiting to connect to peers" and then the right % after
