### ISSUE TITLE
Can't install -- Blockmarket .tar and .zip only has README.md

### ISSUE THREAD

**Issue by Atherz97** [syscoin/blockmarket-desktop-public#256]
And the readme has a link which leads to the same download page.

Has this really been going on for over a month, no Linux users being able to use Blockmarket?

**Comment by sidhujag** [comment]
Theres no linux version yet for the wrapper that runs BM.. only osx or win32/64 right now

**Comment by Atherz97** [comment]
Okay. When's the release date for us?

**Comment by dwasyluk** [comment]
There is no linux version yet but we're working on producing one as soon as possible.
