### ISSUE TITLE
Console (syscoin-api) in BM 1.1 returns error for certain endpoints

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#261]
Some console cmds do not work for instance importprivate key gives this error. 

TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
--

**Comment by dwasyluk** [comment]
This actually might be an issue with syscoin-api (used by BM). We'll investigate this one.

**Comment by dwasyluk** [comment]
On further review this impacts several endpoints (none of which are directly used by blockmarket). We'll need to go thru the full list of get requests in syscoin-api and update get requests that improperly use body w/get requests.

**Comment by sschepis** [comment]
I've updated all APIs which passed in typed data in body but were set to GET to POST. This should fix the issue but it needs a retest

**Comment by dwasyluk** [comment]
@johnp1954 this should be fixed, please retest and close.

**Comment by jnessbcf** [comment]
Closing - will split this into separate issues per console command as they are tested.
