### ISSUE TITLE
JavaScript error when updating Alias

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#262]
I created a new Alias using the basic form. 10 minutes later I added identity info using the advanced form - when I clicked Update I got this error

![image](https://user-images.githubusercontent.com/15713199/32369246-659af03a-c080-11e7-8857-7b3b15f52b61.png)

After clicking OK on the error message the update seemed to complete successfully

**Comment by willyko** [comment]
Could you try this in Blockmarket 1.1.1 and see if it's reproducible? Thanks!

**Comment by dwasyluk** [comment]
Need to try to repro this internally- I've seen it but inconsistently.

**Comment by dwasyluk** [comment]
I've not been able to reproduce this in my testing. If @sysmca you're able to consistently reproduce w/steps please feel free to reopen or resubmit.

**Comment by sysmca** [comment]
Yeah seems fine
