### ISSUE TITLE
Can't send a message from my aliases (bug)

### ISSUE THREAD

**Issue by Redrace** [syscoin/blockmarket-desktop-public#265]
Error message:
''Could not lookup alias. Make sure your wallet is unlocked....)

Information:
- Alias: redrace
- Wallet is unlocked
- Sycoin is available
- BM 1.1.1 installed and running
- Already closed and restarted BM
- Alias is an old alias from qt, but I think this can't be the problem
- I can receive messages with the alias though
- Other aliases won't work either

**Comment by willyko** [comment]
Cannot send for any of your aliases? or just that 1 "redrace" alias? Is it possible to create a new alias and see if you can send from that one?

**Comment by Redrace** [comment]
I will try it tomorrow. My other alias wasn't working either at the time of trying. Blockchain was sinked and I could actively use The blockmarket app, but only the messaging didn't work, to no one with either aliases. Tomorrow I will try to create a new one and do it from there. The aliases I tried were both created on the Qt version of Blockmarket. Hope that's the problem, but we will find out tomorrow.

**Comment by dwasyluk** [comment]
@Redrace any update on this one?

**Comment by dwasyluk** [comment]
Haven't gotten a reply on this one, closing.
