### ISSUE TITLE
Create New Receiving Address (label text)

### ISSUE THREAD

**Issue by Slumberland** [syscoin/blockmarket-desktop-public#269]
Whilst creating a new receiving address the label field was not visible.
I thought it was broken because I couldn't see where to enter the field - entered it anyway and my random character efforts were there. I tried it again typing in the desired label I wanted and it saved and displayed correctly. There is now an address with random text label, is it possible to edit it?
MacOS 1.1.1

**Comment by dwasyluk** [comment]
@Slumberland could you please provide a screenshot of what you saw when you say:

> the label field was not visible.

Thanks

**Comment by dwasyluk** [comment]
Closing unless more info is provided, seems to work fine: 
<img width="421" alt="screen shot 2018-01-09 at 10 18 51 pm" src="https://user-images.githubusercontent.com/987186/34754328-1800cfd0-f58b-11e7-926a-7d95b5be9665.png">
