### ISSUE TITLE
Display ALL receiving addresses and respective Aliases on Receiving Address screen

### ISSUE THREAD

**Issue by Keyare** [syscoin/blockmarket-desktop-public#274]
"Receiving address" screen should show all addresses including alias addresses and the totals.
This will reduce support requests to explain change addresses and balance discrepancies.

Current user experience can cause confusion:
![image](https://user-images.githubusercontent.com/7099087/33402458-7d7b96e6-d511-11e7-90c8-bbcf47de59ac.png)

**Comment by dwasyluk** [comment]
@Keyare this should be fixed, please retest and close.

**Comment by willyko** [comment]
Fix confirmed
