### ISSUE TITLE
Alias creation issues (1.1.2)

### ISSUE THREAD

**Issue by vensko** [syscoin/blockmarket-desktop-public#279]
Starting with advanced form:
Entered "dzmitry" into "Alias name", filled first name, last name, facebook, twitter, pressed Create New Alias - the button gets disabled and nothing else happens without any errors, alias was not created.
Switched to basic form, filled Alias Name (different capitalization!) and Public Value (what's this? there is no such field in advanced form) with "dzmitry". Pressed Create New Alias - voila, I've got an alias.

After, the blue button in top right corner "Please create an alias" didn't hide until restart and breadcrumbs started to pile up https://imgur.com/cePxV8o .

**Comment by dwasyluk** [comment]
How long did you wait when trying to create the advanced alias? If you didn't wait for a notification (error or success) you might just need to give it a few seconds longer. Sounds like latency, pls provide more info on what you experienced/how long you waited/how many times you reproduced this scenario. Thanks.

**Comment by vensko** [comment]
I waited for at least 10 seconds. Just tried to create a new alias through advanced form, gave it a couple of minutes and got the same result - no alias, no notification. Is there a human readable log or a console where I can see what happens?

**Comment by dwasyluk** [comment]
Yeah, run the app with the `--dev` flag and then use the tools menu to open devTools and then its just normal console stuff as you would any other app. See if there is an error occuring that's not being reported to the user.

**Comment by vensko** [comment]
![pic](https://i.imgur.com/gqBDxrf.png)

**Comment by dwasyluk** [comment]
@vensko can you post the full JSON of the identity you're trying to create? Thanks, that screencap is useful, def failing against the payload your sending w the identity.

**Comment by vensko** [comment]
![pic](https://i.imgur.com/mSGcaXw.png)

**Comment by dwasyluk** [comment]
@vensko there have been some key improvements to this flow since you've logged this issue and in trying to recreate the issue I'm unable to in the latest 1.1.4 release. Can you please retest in 1.1.4 and let us know if this is still occurring?

**Comment by vensko** [comment]
Seems like fixed, can't reproduce anymore.

**Comment by vensko** [comment]
Although have another issues with created alias:
![pic](https://i.imgur.com/QBbtOUY.png)

**Comment by vensko** [comment]
![pic](https://i.imgur.com/w5eiI8h.png)

**Comment by vensko** [comment]
I tried "Update Alias", and it didn't fix that.

**Comment by vensko** [comment]
The error above reported here #307
