### ISSUE TITLE
Fix paddings and margins

### ISSUE THREAD

**Issue by vensko** [syscoin/blockmarket-desktop-public#280]
![pic](https://i.imgur.com/IyHUoUK.png)

![pic](https://i.imgur.com/iPCTbFd.png)

![pic](https://i.imgur.com/bq3VTsY.png)

![pic](https://i.imgur.com/RJCZs8S.png)

**Comment by dwasyluk** [comment]
These are all addressed except for the category list, that will be spit into a separate issue as the styling of that component needs work.

**Comment by dwasyluk** [comment]
@vensko this should be fixed, please retest and close. The browse padding has been split off as #284.

**Comment by vensko** [comment]
A bit more:
![pic](https://i.imgur.com/21PJALz.png)

![pic](https://i.imgur.com/ixNYGdG.png)

![pic](https://i.imgur.com/UD29lv6.png)

**Comment by dwasyluk** [comment]
Closing this but persisting any further reported issues in #284. 👍
