### ISSUE TITLE
Margins and padding continued

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#284]
![68747470733a2f2f692e696d6775722e636f6d2f524a435a7338532e706e67](https://user-images.githubusercontent.com/987186/33789256-50f4aabe-dc45-11e7-9ee6-ec41d42bc3ef.png)

**Comment by dwasyluk** [comment]
More info split from #280:
A bit more:
![pic](https://i.imgur.com/21PJALz.png)

![pic](https://i.imgur.com/ixNYGdG.png)

![pic](https://i.imgur.com/UD29lv6.png)

Thanks @vensko

**Comment by bf-jira-integration** [comment]
test
