### ISSUE TITLE
Code is showing on bottom of "new offer" page

### ISSUE THREAD

**Issue by syshodlor** [syscoin/blockmarket-desktop-public#29]
The following code shows up at the bottom of the "new offer" page on windows:

{
  "sellerAlias": "",
  "title": "",
  "description": "",
  "category": "",
  "price": 1,
  "quantity": "1",
  "certguid": "",
  "paymentOptionsDisplay": "SYS",
  "currency": "SYS",
  "geolocation": "",
  "safeSearch": "Yes",
  "isPrivate": "false",
  "commission": 0
}

**Comment by dwasyluk** [comment]
Fixed in beta2 please retest.

**Comment by sebastien1234** [comment]
confirmed no longer showing in beta 2 closing #29
