### ISSUE TITLE
Incoming payment stuck

### ISSUE THREAD

**Issue by coinsinpocket** [syscoin/blockmarket-desktop-public#294]
Hi there,

I am using the latest Blockmarket wallet. My ballance appears fine, but there is one incoming transaction
that seems stuck, The is the spinning arrow icon next to the transaction, and it won't dissapers/resolve.

I have been on the telegram and slack, and they suggested to post here, to see if you guys might be able to assist. Thanks for any help that you can give me.

**Comment by dwasyluk** [comment]
I think this was due to our seeds being down and your wallet not being able to synchronize with the network to get the payment you're referring to. Please let me know if you still need help.

**Comment by coinsinpocket** [comment]
Hello dwasyluk, thank for for your reply. Sorry for the late response. Been very busy (life and work)

I think that the payment is in my wallet/ballance. But is just not updating.

I did have problems with payments last year. Where I did not move over from a much older wallet to the current wallet and the great guys at Syscoin helped me resolve the issue.

I do still need help. Thank you.
