### ISSUE TITLE
Fund Manager currency selection full name and logo

### ISSUE THREAD

**Issue by willyko** [syscoin/blockmarket-desktop-public#299]
Nice to have enhancement
Add crypto's full name and the logo in the drop down list

![screenshot 2018-01-11 18 09 08](https://user-images.githubusercontent.com/11524904/35019643-c95ffdae-fadc-11e7-80e9-a53ce5390faf.png)

**Comment by doublesharp** [comment]
![image](https://user-images.githubusercontent.com/571472/36634341-00735694-1958-11e8-99b8-21bf2c0d954a.png)
