### ISSUE TITLE
Can't buy more than 1 of an item in the market.

### ISSUE THREAD

**Issue by jeroenvanwissen** [syscoin/blockmarket-desktop-public#30]
When buying an item from the marketplace and change the Quantity to 2, the application throws an error.

Error: Parameter (request) failed schema validation

**Comment by jeroenvanwissen** [comment]
Beter tested:

By default the quantity is an integer, set to 1.
When changing the quantity, it becomes a string. And send to the API as a string, which is not accepted by the API validator.

Needs some typecasting.

**Comment by dwasyluk** [comment]
Thanks for the details, should be a quick fix 👍

**Comment by sidhujag** [comment]
please retest in beta2

**Comment by jeroenvanwissen** [comment]
Works 👍
