### ISSUE TITLE
BM Beta UI won't reopen unless quit and then reopen Mac machine v 10.11.6

### ISSUE THREAD

**Issue by p5global** [syscoin/blockmarket-desktop-public#31]
Mac ver 10.11.6 issue: After the initial launch of wallet, if I close it, it doesn't reopen unless I "quit" the application in the Mac dock and then go into Launch and relaunch it.

**Comment by dwasyluk** [comment]
This is normal mac behavior as far as I know, same thing happens with QT. If you "close" the QT wallet via the "X" it is still running. You must quit via CMD+Q or a quit-menu as you described for the application to be terminated, "X" is the same a "minimize" in the Mac context for many applications and we want to keep consistent with that.

**Comment by dwasyluk** [comment]
Reopening this after talking to @jeroenvanwissen as he caught that even tho this does minimize the app to dock, you're unable to restore afterwards which is not the desired behavior.

**Comment by p5global** [comment]
Correct, Dan. But it seems to be working fine now in Beta3. I'll let you know for sure once I've made a couple of purchases, and minimized the screen a few times. But, BMBeta3 hasn't locked up on my yet. 
 

Sent: Monday, May 29, 2017 at 6:03 PM

**Comment by dwasyluk** [comment]
Closing as beta.
