### ISSUE TITLE
Wallet.dat

### ISSUE THREAD

**Issue by cihanozbek** [syscoin/blockmarket-desktop-public#317]
Hi, i want to back up blockmarket wallet but wallet.dat: DB_VERIFY_BAD: Database verification failed
__db_meta_setup: C:\Users\aliba\AppData\Roaming\Syscoin\wallet.dat: unexpected file type or format

Please,help me

**Comment by dwasyluk** [comment]
Please jump in our Slack and use the #help channel- happy to help you with this!
