### ISSUE TITLE
BM Beta UI won't open Mac machine v 10.12.4

### ISSUE THREAD

**Issue by peekay69** [syscoin/blockmarket-desktop-public#32]
![screen shot 2017-05-10 at 6 30 18 am](https://cloud.githubusercontent.com/assets/28594481/25894582/5af91da8-354a-11e7-869e-755066fc8c93.png)

**Comment by peekay69** [comment]
I tried quitting and reopening but it still won't load. All I see are the spinning gears.

**Comment by peekay69** [comment]
![screen shot 2017-05-10 at 6 33 16 am](https://cloud.githubusercontent.com/assets/28594481/25894659/b151ccae-354a-11e7-927d-b620d2d01517.png)

**Comment by dwasyluk** [comment]
Closing as duplicated of #24
