### ISSUE TITLE
Source code tarball always empty

### ISSUE THREAD

**Issue by novize001** [syscoin/blockmarket-desktop-public#324]
Hi there,

I'm using Linux, so I have to download and compile the source code on my own (no binaries for Linux so far). However, when I'm trying to download the latest source code, there is only an README.md file included. This also applies to version 1.1.4.

Can somebody please upload the full source code? Otherwise I'm unable to use the Syscoin blockmarket desktop software at all. I'm a Linux only user.

Best regards

**Comment by willyko** [comment]
Blockmarket desktop doesn't support linux at this moment, and it's a close-sourced project so we will not be able to publish the code.
