### ISSUE TITLE
Encrypted wallet / password support and experience

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#34]
No option to set password etc

**Comment by sidhujag** [comment]
where? you can set alias password in the new or edit alias screen.

**Comment by johnp1954** [comment]
I mean a password for your Wallet

**Comment by dwasyluk** [comment]
Yea we need (in regards to pw/encrypted wallets):
* indicator that wallet is encrypted
* way to encrypt wallet
* way to change password
* way to "unlock" wallet

Will be nice to do this right, QT locking experience is 💩

**Comment by johnp1954** [comment]
This needs doing before final release

**Comment by dwasyluk** [comment]
agreed, the functions are there in the syscoin-api server, we will support this for public release.

**Comment by sidhujag** [comment]
looks good, just need to change pw
