### ISSUE TITLE
Blockmarket desktop menu broken, unable to send / recieve

### ISSUE THREAD

**Issue by CharlieSmith** [syscoin/blockmarket-desktop-public#349]
Just loaded up blockmarket and allowed it to sync, the menu system is broken and not displayed correctly and even when It does show up none of the menu items work such as send / receive.

Please help. 

![untitled](https://user-images.githubusercontent.com/3805110/39094811-d090a762-462d-11e8-97d9-5daca1ac49c9.png)
![blockmarket](https://user-images.githubusercontent.com/3805110/39094813-d816a09a-462d-11e8-8e29-5e4782f7e03e.jpg)

**Comment by CharlieSmith** [comment]
Anybody?

**Comment by CharlieSmith** [comment]
?

**Comment by CharlieSmith** [comment]
I backed up my wallet and priv key and installed updated block market which solved problem, no thanks to the support team. I've cashed out now this issue has highlighted the lack of support / effort by dev team who are probably on boats with hoes ATM, syscoin could be great but is looking like just another scamcoin, devs got rich and sold out.

**Comment by locutus75** [comment]
Smug, show some respect.  Haven't come across a team who is more dedicated and work their absolute best. You clearly don't need to be here. Bye.

**Comment by sidhujag** [comment]
retest in new bm desktop
