### ISSUE TITLE
BM 1.2.3 Not syncing 100% of blocks (despite showing Sync as complete)

### ISSUE THREAD

**Issue by eljayuk** [syscoin/blockmarket-desktop-public#351]
Block market 1.2.3 has not completed it's sync with the chain; it's last block is currently showing as May 21st, block 706692. It shows as 100% sync'd. 

I have transferred funds to my wallet address but these transactions occurred after the above date they are not registering in BM. I am therefore not able to create alias' / etc. 

This originally occurred with BM 1.1.4; i upgraded to 1.2.3 to see if the issue had been resolved.

**Comment by doublesharp** [comment]
Blockmarket 1.x only works with the Syscoin 2.x blockchain which was hard forked and retired in favor of Syscoin 3.x at the beginning of May. As this chain is no longer active it will not sync.
