### ISSUE TITLE
Problem with closing BM3 on MacOS

### ISSUE THREAD

**Issue by cradox** [syscoin/blockmarket-desktop-public#359]
When I try to close the BM3 application, a message appears as on the attached printscreen

<img width="521" alt="zrzut ekranu 2018-06-26 o 11 50 14" src="https://user-images.githubusercontent.com/39410933/41908408-22d76aee-7944-11e8-90bc-b5d1a820b259.png">

**Comment by jnessbcf** [comment]
@cradox Can you generate this issue consistently on closing?

**Comment by cradox** [comment]
the problem no longer occurs
