### ISSUE TITLE
Can you send CPS coin now 2/7/2018

### ISSUE THREAD

**Issue by elmany2025** [syscoin/blockmarket-desktop-public#372]
Can you send CPS coin now 2/7/2018

**Comment by einalex** [comment]
please direct your request at coinpayments.net

**Comment by elmany2025** [comment]
I have 11000 pieces and I want to convert them to another work or pull them out

**Comment by elmany2025** [comment]
![35328353_1387893821354222_5497922322041929728_n](https://user-images.githubusercontent.com/28968066/42176647-7fe39dcc-7dde-11e8-847a-1737f22b5653.jpg)

**Comment by jnessbcf** [comment]
As stated in another thread, CPS coin doesn't have anything to do with SYS (other than this was the mechanism by which the airdrop occurred) and certainly nothing to do with Blockmarket Desktop, which is what this issue repository is for.  =)  

Would suggest these questions be directed to coinpayments.net.    Closing.
