### ISSUE TITLE
How to convert cps coin to btc

### ISSUE THREAD

**Issue by elmany2025** [syscoin/blockmarket-desktop-public#373]
How to convert cps coin to btc
![35328353_1387893821354222_5497922322041929728_n](https://user-images.githubusercontent.com/28968066/42177054-1687d0e4-7de0-11e8-845f-bae36969c498.jpg)

**Comment by sysmca** [comment]
This is the Syscoin GitHub, why are you posting this here? Try the Coin Payments website/Telegram/Twitter for support...

**Comment by jnessbcf** [comment]
CPS coin is related to CPS and CPS only.  It doesn't really have much to do with SYS (other than that's how it was distributed) and it certainly has nothing to the Blockmarket Desktop product =).  Closing.
