### ISSUE TITLE
Assets do not display

### ISSUE THREAD

**Issue by byronmil** [syscoin/blockmarket-desktop-public#374]
After creating an asset, it does not display in Assets > Assets in BM3.

**Steps to Recreate**
- Create an asset
- Navigate to Assets > Assets, asset dot display

**Troubleshooting**
- After a restart, my asset displays
- After a later restart, my asset does not display
- Tools > Reindex Blockmarket
- After the sync, my asset displays
- After a later restart, my asset does not display
- My asset not displaying is much more frequent than the times it does display in Assets > Assets.

All I see when navigating to Assets > Assets is the Assets Heading and `No assets found.`

**Comment by byronmil** [comment]
User error. I had an alias selected. Assets do display when I select `All Accounts` or the alias used to create the asset.

**Comment by jnessbcf** [comment]
I’ve re-opened this issue - we should be making it much clearer in the UI as to which aliases assets are being used.

Thanks Byron!!
