### ISSUE TITLE
Enhancement Request: `Browse Marketplace` landing page should excite users

### ISSUE THREAD

**Issue by byronmil** [syscoin/blockmarket-desktop-public#375]
**Problem:**
When navigating to Marketplace > Browse Marketplace (or any category thereinafter), users are presented with 5, what appear to be, random listings on the landing page. This is extremely uninteresting for users and, instead, should grab their attention. Currently, the page is 3 disabled products, two active products and one with an image. 

**Ideas**
- Featured categories and products on the main marketplace page
  - Most viewed, best sellers, hot deals.
- Increase the default number to 20 or 50
- Add a pagination selection and navigation to the top of the page
- Add Child Categories:
  - Electronics
    - Cameras
    - Computers
    - Computer Hardware
    - Phones
    - TVs

**Comment by jnessbcf** [comment]
💯 Much agreed that this **badly** needs some sexing up.  While I can't guarantee where/when this will show up in the roadmap it will be put into our overall backlog.

**Comment by 2ge** [comment]
I was about open exactly same issue. Also show only active listings, not "invalid alias error".
