### ISSUE TITLE
Enhancement: create a dropdown for categories

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#39]
Can the category be a drop down listing the existing ones and the option to add new

**Comment by dwasyluk** [comment]
We should have a dropdown list both in the offer and certificate pages as well as a category component in the offer browse screen.

**Comment by dwasyluk** [comment]
Related to #45

**Comment by sidhujag** [comment]
looks good, can't create new, its set by a github repo controlled json file.
