### ISSUE TITLE
Blank "seller" field on my purchases screen

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#42]
On this screen it show brought and sold items also does not show seller detail

![image](https://cloud.githubusercontent.com/assets/16462796/25915817/8d3840b2-35ba-11e7-8e59-915ecc06467c.png)

**Comment by dwasyluk** [comment]
@johnp1954 are you saying its showing purchases and sales in the "purchases" tab (in addition to blank seller name)?

**Comment by johnp1954** [comment]
Yes if you look at 'Just a Test' that was brought of me by alwoss

**Comment by dwasyluk** [comment]
This should be fixed in beta3.

**Comment by johnp1954** [comment]
Fixed
