### ISSUE TITLE
Sending to alias you own does not show in txlist

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#44]
Send some sys to an Alias I own no record of it happening on transactions

**Comment by sebastien1234** [comment]
is that within the same wallet @johnp1954 ? does a transaction appear after you close and reopen the wallet?

**Comment by johnp1954** [comment]
Yes within the same wallet and it does not appear after opening and closing

John


On 11 May 2017, at 01:52, sebastien1234 <notifications@github.com<mailto:notifications@github.com>> wrote:


is that within the same wallet @johnp1954<https://github.com/johnp1954> ? does a transaction appear after you close and reopen the wallet?

**Comment by dwasyluk** [comment]
@johnp1954 does this only happen when you send to an alias? ie: if you send to a SYS address, close and reopen BM b1 you see the tx- but do same when sending to alias and you _**do not**_ see it? Just trying to narrow scope, thanks!

**Comment by johnp1954** [comment]
This ONLY happens when you send to an alias you own ie send to yourself

**Comment by dwasyluk** [comment]
Perfect thanks for the additional info, very helpful 👍

**Comment by sidhujag** [comment]
retest in beta2

**Comment by johnp1954** [comment]
Not Fixed

**Comment by sebastien1234** [comment]
confirmed not fixed @dwasyluk sending to self does not generate a transaction and does not change the balance of said alias

**Comment by johnp1954** [comment]
Not fixed changes alias balance but no TX is shown even after closing and opening

**Comment by willyko** [comment]
Confirm that TX is not shown in recent transaction table.  SYS does get moved to the alias and debug mode shows a valid txid as "send to address response".  
@sidhujag could you comment on this?

**Comment by sidhujag** [comment]
If sys does get moved this its fine, retest in bm web

**Comment by johnp1954** [comment]
Is this fixed in BM 1.1

**Comment by sidhujag** [comment]
No

**Comment by dwasyluk** [comment]
closing as duplicate of #259
