### ISSUE TITLE
Cannot choose different category for Certificates than "certificates"

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#45]
Creating a new cert and change the Category to something get an error must use Certificate category what are these and where do i fingdthem

**Comment by sebastien1234** [comment]
This is the error you receive by choosing any other category than Certificates

![image](https://cloud.githubusercontent.com/assets/7034589/25927341/64d45756-35c3-11e7-888f-6a521719b226.png)

**Comment by dwasyluk** [comment]
This is WIP for b5

**Comment by sidhujag** [comment]
retest in b5a

**Comment by willyko** [comment]
retested this and looks like the category field for new certificate now accepts any string that starts with "certificates".  So I created an offer with category "certificatesasdfasdfasdfasdfajshdgakl;sjga;lkwjl;awjfl;asjdgl;kajsl;ahfl;bnal;fjbn;lamsgbasfas"

see cert guid 0b1aa05ce9a34d26

don't think this is working as intended

**Comment by johnp1954** [comment]
This is not fixed you can still type what you like there is no drop down

**Comment by sidhujag** [comment]
There is no category dropdown.the issue is not about the dropdown but there was a bug that it wasnt checking for certificates in case insensitive manor before. The scope of the issue has nothing to do with dropdowns. That is another issue (which imo does not exist)

**Comment by sidhujag** [comment]
There is no category dropdown.the issue is not about the dropdown but there was a bug that it wasnt checking for certificates in case insensitive manor before. Maybe we can add a typeahead there when you type category

**Comment by johnp1954** [comment]
There was a suggestion that a drop could be added i see you have closed it, The issue I raised here was that you can type what you like and get and error must use Certificate category. To a user this means nothing

**Comment by sidhujag** [comment]
Right with errorcode it will link to documentation however.. theres so many combinations of things that can happenthats why i included error codes so they be looked up with more details.

**Comment by johnp1954** [comment]
Of there is a drop down now so issue closed
