### ISSUE TITLE
radio buttons should default to an option and not allow unselected *updated to certificates only*

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/blockmarket-desktop-public#46]
new alias:
![image](https://cloud.githubusercontent.com/assets/7034589/25927410/d7708d02-35c3-11e7-8bbd-3feb32470166.png)

New certificate:
![image](https://cloud.githubusercontent.com/assets/7034589/25927427/f263048c-35c3-11e7-917a-6110c0c65c42.png)

**Comment by sidhujag** [comment]
please retest in beta2

**Comment by sebastien1234** [comment]
@dwasyluk this is fixed for aliases/new offer but not for certificates:

![image](https://cloud.githubusercontent.com/assets/7034589/26138208/64f42974-3a95-11e7-9cf0-85ba6f774563.png)

**Comment by dwasyluk** [comment]
Should be fixed for certs as well as aliases and offers pls retest in b3

**Comment by sebastien1234** [comment]
fixed in beta 3, close #46
