### ISSUE TITLE
Current balance in header doesn't update

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#47]
I got sent some test sys. The balance updated on the homepage but not in the header

![image](https://cloud.githubusercontent.com/assets/15713199/25952083/884824d0-3657-11e7-86f4-bcd9cf4dff71.png)

**Comment by sidhujag** [comment]
please retest in b2

**Comment by dwasyluk** [comment]
@sysmca pls retest in b2 when possible

**Comment by sebastien1234** [comment]
Homepage balance now matches "all aliases" balance . Close #47
