### ISSUE TITLE
sending a message to myself or a non existent alias does nothing

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#5]
originally submitted by @sebastien1234 

need error messages if the message send is not possible,

tried sending a message to myself, nothing happens
tried sending a message to an alias that does not exist, nothing happens
tried sending a message to an alias that does exist, received confirmation many seconds later, making it look like it did not work initially

**Comment by dwasyluk** [comment]
We now return RPC errors to the user as notifications, so you should see the reasons these operations failed.
