### ISSUE TITLE
Duplicate entry while amending for sale product

### ISSUE THREAD

**Issue by cbassthefish1** [syscoin/blockmarket-desktop-public#50]
I recently tried to sell my wife on the testnet, however it resulted in a duplicate entry when I decided to amend some details on my sale. I now have 2 for sale but only have one wife :(

**Comment by sidhujag** [comment]
Set one to private

**Comment by sebastien1234** [comment]
As Jag stated, you can set the offer to private and it will no longer be listed, you can also set the quantity to 0 so it will not be listed publicly; you could get a second wife as well, but let's look further into this :) @cbassthefish1 I'm not seeing this error when making a change to an existing offer, can you provide step-by-step what you did exactly? I've tried updating the quantity as well as the description, title and price and I still have only one offer. Please let us know :)

**Comment by cbassthefish1** [comment]
Ok, I realise what I have done. I resubmitted the same order twice after amending the description and clicked "Create New Offer". This is not a bug. Although from a user point of view it might be easy to duplicate your submission without wanting to do so. Food for thought here. Either remove the "Create New Offer" Button after submission (Not good as I might want to create multiple new offers quickly and easily based on the same information), or leave the offer page (not good, same as last reason) or add an additional button which states "Update Last Offer" so you have two buttons to update last or create new.

**Comment by dwasyluk** [comment]
Closing this as it should be correct/curtailed by #91 👍 in b3
