### ISSUE TITLE
Safe Search is ambiguous

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#55]
Not clear if it means:

1) This item is safe for all to search, or
2) This item should be hidden by the Safe Search filter

It is named differently on New Cert tab and New offer Tab:

![image](https://cloud.githubusercontent.com/assets/15713199/25987715/0ff285f2-36ed-11e7-9b4e-1c4e7080fe17.png)

![image](https://cloud.githubusercontent.com/assets/15713199/25987720/1412abd0-36ed-11e7-831f-079066cb98f1.png)

**Comment by sidhujag** [comment]
retest in beta2, note that global ss filter not in yet, test for other aspects of this issue

**Comment by sebastien1234** [comment]
wording change, closing #55
