### ISSUE TITLE
Offers with linked certs are forced to use certificates category

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#56]
When creating an offer with a linked cert, you must use the 'certificates' category

This will make it hard to search for items like video game Steam keys

**Comment by sebastien1234** [comment]
This is also the case for creating the certificate itself, see issue #45

**Comment by sidhujag** [comment]
you can always use subcategories like certificates > game codes > steam aslong as it "starts" with certificates as first level it will be accepted.
