### ISSUE TITLE
Offers with linked certs don't show up in Marketplace

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#57]
I created an offer, linked a cert to it, it did not appear in the Browse Marketplace screen.

offeractivate TX: 2069fec05e57e55033fb104bc782fcd6ece794de0c0294c36792976f06d0c592

cert ID: dcea436434daef03

**Comment by sebastien1234** [comment]
@sysmca I tried to reproduce your issue and I'm not having this problem, it did however take some time to get to the browse section and required me to close and reopen BM to see the offer. 

The offer, however, does not indicate that it has a cert in it. @sysmca is it possible that you set it to private or safe-search off? Can you try to accept this offer and see if you received a certificate?:

eff34db2073d8a09

![image](https://cloud.githubusercontent.com/assets/7034589/26006704/6fa76f44-370b-11e7-9c75-0192387646b4.png)

**Comment by sysmca** [comment]
couldn't find that offer

**Comment by sysmca** [comment]
Seems fine now
