### ISSUE TITLE
No way to view OfferID of items you list?

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#58]
I can't seem to find OfferIDs for items I've listed

The 'Items for Sale' tab doesn't show as much info as the 'Purchases' tab. It should also show quantity available, OfferID, Date listed

**Comment by sidhujag** [comment]
retest in beta2

**Comment by sebastien1234** [comment]
items for sale now shows offer id, qty remaining, last updated. closing #58
