### ISSUE TITLE
weird mouse-hover on "send" button

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#6]
originally submitted by @sebastien1234

when you hover over the send button half of it turns yellow

![image](https://cloud.githubusercontent.com/assets/24413854/25871474/990c8974-34d5-11e7-9798-4a1f35ce5c2e.png)

**Comment by dwasyluk** [comment]
This on windows?

**Comment by sebastien1234** [comment]
yes @dwasyluk still happens in current version, this only appears to happen in the send message screen.
