### ISSUE TITLE
refresh functionality required

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/blockmarket-desktop-public#60]
All screens should have a refresh button so you don't have to close and reopen the wallet to refresh. Ideally, all screens would just refresh automatically every minute or so.

**Comment by sidhujag** [comment]
Retest in beta2

**Comment by dwasyluk** [comment]
Screens should refresh automatically but we will put a lil button in top right identity chooser that also allows for manual refresh if user wants to  "make sure" they're up to date.

**Comment by sebastien1234** [comment]
awesome-town indeed @dwasyluk close #60
