### ISSUE TITLE
Weird break in marketplace listings (browse)/previews not the same size

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/blockmarket-desktop-public#61]
There appears to be weird breaks that prevent offers from being properly organized, see bottom first image is the beginning and last is the end. Notice that the preview boxes are all different in size, which may be causing this issue. Preview should be the same size across the board.

Beginning of listings: 

![image](https://cloud.githubusercontent.com/assets/7034589/26008251/f518887e-3711-11e7-9f7c-669ab6c27bd0.png)

End of listings:
![image](https://cloud.githubusercontent.com/assets/7034589/26008275/0b55e53c-3712-11e7-9670-2f55d45a4e83.png)

**Comment by sidhujag** [comment]
I had this issue with a problem I had at my work and the way I solved it was to detect max box size for each row and resize all other boxes in the same row to the same size, that way the grid is uniform. It is a post-process step after your html is loaded.

**Comment by sebastien1234** [comment]
beta 3 seems to have resolved issue, close #61
