### ISSUE TITLE
Cannot delete posting

### ISSUE THREAD

**Issue by peekay69** [syscoin/blockmarket-desktop-public#62]
I'm trying to delete a duplicate item for sale but cannot

**Comment by sidhujag** [comment]
Set to private

**Comment by dwasyluk** [comment]
We could improve the experience by having a "Delete listing" button that really just submits the listing with private=true and qty=0 but it will still show in "your" @peekay69 offer list since you own it, this what your looking for?

**Comment by peekay69** [comment]
No longer possible to create duplicates. Cool!
