### ISSUE TITLE
Doesn't exit screen when I finish creating a new offer

### ISSUE THREAD

**Issue by peekay69** [syscoin/blockmarket-desktop-public#64]
When I click on "new offer" the BM should go to another screen (preferably to my offers screen). It is too easy to create a duplicate offer by pressing on "new offer" again.

**Comment by dwasyluk** [comment]
You should get a notification telling you the offer is being created, once created it should navigate you to the new offer though.

**Comment by peekay69** [comment]
I looked away for a second and didn't see the notification. That`s when I clicked on new offer again and created the duplicate offer

**Comment by peekay69** [comment]
Fixed
