### ISSUE TITLE
Wife for sale was bought but Total Syscoin spent is wrong 

### ISSUE THREAD

**Issue by peekay69** [syscoin/blockmarket-desktop-public#65]
The amount displayed in "Total Syscoin Spent" is wrong
![capture2](https://cloud.githubusercontent.com/assets/28594481/26021887/cac54168-3764-11e7-8365-7bfed3e7e1f7.PNG)

**Comment by sidhujag** [comment]
Retest in beta2

**Comment by sebastien1234** [comment]
![image](https://cloud.githubusercontent.com/assets/7034589/26138642/abeccef0-3a98-11e7-96a2-061474c422b6.png)
amount spent now shows correctly, close #65
