### ISSUE TITLE
Purchase Date does not display date

### ISSUE THREAD

**Issue by peekay69** [syscoin/blockmarket-desktop-public#66]
I just see the time not the date. It should have both.
![capture1](https://cloud.githubusercontent.com/assets/28594481/26021903/074ea3d6-3765-11e7-8f47-ade660f37dd6.PNG)

**Comment by sidhujag** [comment]
Retest in beta2

**Comment by sebastien1234** [comment]
date and  time now displays 
![image](https://cloud.githubusercontent.com/assets/7034589/26138683/ebec602e-3a98-11e7-972a-7bdc77c2f25d.png) closing #66
