### ISSUE TITLE
Bootstrap dropdown broken app-wide

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#67]
Since beta1 changes were made that broke the "dropdown" portion of bootstrap dropdown, they now clip content rather than scrolling long lists, so you cannot access your full list of aliases.

**Comment by dwasyluk** [comment]
Self-assigned this one as I know the cause of this regression and a fix that will maintain the original intent of the first fix while also repairing the regression.

**Comment by sidhujag** [comment]
Is this still valid?
