### ISSUE TITLE
Can't view more than 100txs

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#68]
Changes between b1 and b2 have changed the txlist so only 100txs are visible. Any transactions beyond 100 are no longer displayed or accessible. We need an "load more" or infinite scroll to fix this.

**Comment by dwasyluk** [comment]
This should be fixed by #69 infinite scrolling, so self assigned as I'm working on that atm.

**Comment by willyko** [comment]
fixed in #69
