### ISSUE TITLE
long delay between new cert and notification

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#7]
Originally submitted by @sebastien1234 

notification indicating that new cert was created takes several seconds to first appear, which makes you click it several times and end up creating the certificate many times.

**Comment by cmarsh599** [comment]
Comment from @sidhujag 

Will need a queue of txs waiting for confirm and show it to people

**Comment by dwasyluk** [comment]
yeah we provide more immediate feedback now and a followup when the confirm happens, we can improve this through the top-right indicator as beta progresses.

<img width="1222" alt="screen shot 2017-05-09 at 7 59 49 pm" src="https://cloud.githubusercontent.com/assets/987186/25879335/1c7864c6-34ff-11e7-9a90-6eed43882ea0.png">

**Comment by dwasyluk** [comment]
Closing because this feedback is already there and will be further improved by the top-right component indicating background activity with a tooltip listing exactly which background activities are in progress.
