### ISSUE TITLE
Safesearch/Private confusion solution

### ISSUE THREAD

**Issue by Keyare** [syscoin/blockmarket-desktop-public#75]
Safe search and Private have 4 buttons to choose from and the language is not exactly clear. I suggest removing Safe and Public from the equation and making those defaults.  Simplifying the language to Explicit or Private boolean selections.  See attached. Tooltips in this area could also explain more.
![untitled-1](https://cloud.githubusercontent.com/assets/7099087/26088099/fb89b42c-39a9-11e7-80db-42b5d484a9d9.png)

**Comment by sidhujag** [comment]
Retesr in b4..

**Comment by Keyare** [comment]
Nice
