### ISSUE TITLE
Error when specifying Sys, BTC and ZEC as Payment Options

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#76]
I get the following error when trying to create an offer with all three payment options. 
Error code 1504: Could not validate the payment options.

![image](https://cloud.githubusercontent.com/assets/24413854/26110685/102e80f2-3a21-11e7-9ee1-0f1a38e090b5.png)

**Comment by sidhujag** [comment]
looks good
