### ISSUE TITLE
Character encoding: certain sys service fields show incorrect or encoded data (rather than correct or decoded data)

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#78]
With new character encoding introduced in beta2 to support more languages and richer descriptions the private data field on certificates sometimes now displays the text "undefined". This seems to happen only on private data, should show as blank or "encrypted for owner" but not undefined.

**Comment by willyko** [comment]
creating alias with pub data “test test” will change it to “test%20test” when editing…so if you click update the alias without changing anything it’ll turn into “test%2520test”  
(%20 for spaces and %25 for %)

**Comment by phbart** [comment]
I'm not sure if I understand this issue correctly, but when I update my alias and fill in "test test" in the public value box it does display correctly after updating.

**Comment by sidhujag** [comment]
looks good for now, until they show as errors open specific issues for that
