### ISSUE TITLE
Marketplace Browe not working

### ISSUE THREAD

**Issue by cmarsh599** [syscoin/blockmarket-desktop-public#8]
Originally submitted by @sebastien1234 

Browse offers does not show anything at all, just a "browsing all categories grey box.

I was expecting cats

![image](https://cloud.githubusercontent.com/assets/24413854/25871945/0941dae0-34d7-11e7-98e2-f6f554e2ed14.png)

**Comment by dwasyluk** [comment]
Fixed in b1
