### ISSUE TITLE
Clicking on account balance from dashboard does nothing

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#83]
When you click on More Info on Account balance it does nothing

**Comment by dwasyluk** [comment]
Now takes u to tx list, pls retest in b3

**Comment by frozenfame** [comment]
Same issue for me in b3

**Comment by johnp1954** [comment]
Confirmed NOT fixed Still does nothing

**Comment by sebastien1234** [comment]
confirmed issue still happening on b3 @dwasyluk

**Comment by sidhujag** [comment]
retest in b5

**Comment by sidhujag** [comment]
looks good
