### ISSUE TITLE
Recent transactions on home page dashboard doesn't default to last tx / sometimes populates incorrectly

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#85]
Recent transactions do not default to last TX

**Comment by willyko** [comment]
I'll add to this one:

Homepage's "Recent Syscoin Transactions" is not populated correctly.  It shows "No transactions found", yet clicking "View More" will show that there are indeed transactions in the "Transaction List"

**Comment by sidhujag** [comment]
Those are your recent sys service txs not send rcv coin txs.which will clutter the service tx list
