### ISSUE TITLE
Error when creating alias when alias peg field is incorrect

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#86]
When creating a new alias with just the name field completed you get an error, can not screenshot it for some reason. Win 8 64 bit. You have to put sysrates.peg in to get it to work

**Comment by dwasyluk** [comment]
What's the error?

**Comment by dwasyluk** [comment]
@johnp1954 any followup on this or can this be closed? Please retest this in beta3.

**Comment by johnp1954** [comment]
Fixed
