### ISSUE TITLE
Offer images disappear after navigation to edit offer

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#90]
Created a new offer (Fort) but it does not show for sale it has had loads of confirms

**Comment by johnp1954** [comment]
Offer 81bb65f91e8a7320 now the picture i had has gone

**Comment by Keyare** [comment]
Can confirm.
1) I create an offer and screenshot the my offers page:
![image](https://cloud.githubusercontent.com/assets/7099087/26128364/0a3ce0ce-3a41-11e7-81f3-0c25b9fd93c6.png)
2) I select the offer and go to the edit offers page and do nothing.
![image](https://cloud.githubusercontent.com/assets/7099087/26128380/1c65a07e-3a41-11e7-8ca0-b99d16c4be3e.png)
3) When I go back to the My Offers page my images are gone.
![image](https://cloud.githubusercontent.com/assets/7099087/26128409/375966e0-3a41-11e7-993a-a7b1a8a756a0.png)
4) And now when I select that offer, all the images are missing from the offer
![image](https://cloud.githubusercontent.com/assets/7099087/26128436/4ca7aed0-3a41-11e7-8b00-06865db4eca8.png)

Restarting fixes this.

**Comment by dwasyluk** [comment]
Fixed via fb087801491e07277a33bb872304a2ba1f422373 pls retest in b3.

**Comment by johnp1954** [comment]
Fixed
