### ISSUE TITLE
Disable submission button while confirms are pending

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#91]
On forms where there is a submit action, if the form contents are valid and submitted to the blockchain the submit button should be disabled until an error is returned. If no error is returned, take the user somewhere meaningful based on their context.

Right now they can "hammer" the offernew button and create many, duplicate offers.

**Comment by dwasyluk** [comment]
Also see #110 for another UX scenario we should cover prior to disabling the buttons.

**Comment by dwasyluk** [comment]
pls retest in b3

**Comment by frozenfame** [comment]
This is working for me.

**Comment by phbart** [comment]
I can also confirm this works
