### ISSUE TITLE
Sending sys, posting, replies, anything that is an action out going

### ISSUE THREAD

**Issue by Alternating** [syscoin/blockmarket-desktop-public#92]
Basically this needs a confirmation page so someone doesn't keep sending/posting/replying over and over and over and over again..

**Comment by dwasyluk** [comment]
See #110 for another scenario.

**Comment by dwasyluk** [comment]
Closing as dupe of #91, will include note there about #110.

**Comment by dwasyluk** [comment]
Between #91 and #110 this case is covered.
