### ISSUE TITLE
Notify user on external SYS service activity and update local data.

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#94]
When funds are received, or offers accepted, messages received, or aliases transferred- the recipient BM interface should display an appropriate notification.

Also, the data becomes stale at this point, requiring refresh to show proper info in regards to things like offers sold/ still for sale.

**Comment by sidhujag** [comment]
Retest in b4

**Comment by sidhujag** [comment]
looks good
