### ISSUE TITLE
Show alias-specific tx list operations on main tx list

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/blockmarket-desktop-public#96]
In "All Aliases" tx list we no longer display alias-specific operations, like alias activated, we should be able to get this info from the new metadata object on transactions.

**Comment by dwasyluk** [comment]
As seen in attached image alias activate, update, certnew, etc are now shown in tx list (dashboard or main):

![image](https://cloud.githubusercontent.com/assets/987186/26127425/4ffabdc8-3a57-11e7-9642-3c6e04f22460.png)

**Comment by sidhujag** [comment]
Retest in b4

**Comment by sidhujag** [comment]
looks good
