### ISSUE TITLE
New certificate has no create (submit) button

### ISSUE THREAD

**Issue by willyko** [syscoin/blockmarket-desktop-public#99]
OS: Windows 10
In New Certificate page, there is no button for form submission

**Comment by sebastien1234** [comment]
![image](https://cloud.githubusercontent.com/assets/7034589/26137411/00f7ecc6-3a90-11e7-9e9e-c454686ec758.png)
confirm same issue windows 10 / 64bit

**Comment by dwasyluk** [comment]
Fixed pls retest in b3.

**Comment by phbart** [comment]
I have been able to succesfully create a new certificate in beta 3

**Comment by willyko** [comment]
fix confirmed in beta 5
